import assert from "node:assert/strict";import test from "node:test";import {MemoryOperationLedgerRepository} from "../lib/operation-ledger";import {createPublishAuthorization} from "../lib/publish-authorization";import {createListingFingerprint} from "../lib/candidate-fingerprint";import {executeAuthorizedPublishTransaction,PublishAmbiguousResultError,type AuthorizedPublishProvider} from "../lib/authorized-publish-transaction";
const FP="a".repeat(64),NOW="2026-09-05T09:00:00.000Z";const read={title:"Planner",description:"Desc",price:14.9,tags:["one","two"],quantity:999,who_made:"i_did",when_made:"2020_2025",taxonomy_id:123,type:"download",state:"draft"};const LFP=createListingFingerprint({title:"Planner",description:"Desc",priceUsd:14.9,tags:["one","two"],quantity:999,who_made:"i_did",when_made:"2020_2025",taxonomy_id:123,type:"download",state:"draft"});
function grant(){return createPublishAuthorization({authorizationId:"AUTH",candidateId:"CAND",candidateFingerprint:FP,channel:"etsy",shopId:"SHOP",draftListingId:"DRAFT",issuedAt:"2026-09-05T08:59:00.000Z"});}function input(overrides:any={}){return{operationId:"OP-PUB",authorization:grant(),candidateId:"CAND",candidateFingerprint:FP,expectedListingFingerprint:LFP,shopId:"SHOP",draftListingId:"DRAFT",channel:"etsy",now:NOW,...overrides};}
class Provider implements AuthorizedPublishProvider{publishes=0;reads=0;published:any=null;ambiguous=false;drift=false;async readDraft(){this.reads++;return this.drift?{...read,title:"Drift"}:read;}async publish(){this.publishes++;this.published={listingId:"LIVE-1",state:"active"};if(this.ambiguous)throw new PublishAmbiguousResultError();return this.published;}async readPublished(){return this.published;}}
test("exact pre-read authorization publishes once and confirms post-read",async()=>{const r=new MemoryOperationLedgerRepository(),p=new Provider();const x=await executeAuthorizedPublishTransaction(r,p,input());assert.equal(x.status,"PUBLISHED");assert.equal(p.publishes,1);assert.equal(x.authorization.authorization.state,"CONSUMED");});
test("identity mismatch stops before authorization consumption or publish",async()=>{const r=new MemoryOperationLedgerRepository(),p=new Provider();p.drift=true;const x=await executeAuthorizedPublishTransaction(r,p,input());assert.equal(x.status,"IDENTITY_MISMATCH");assert.equal(p.publishes,0);assert.equal(x.authorization.authorization.state,"ACTIVE");});
test("authorization candidate mismatch performs no publish",async()=>{const r=new MemoryOperationLedgerRepository(),p=new Provider();await assert.rejects(()=>executeAuthorizedPublishTransaction(r,p,input({candidateId:"OTHER"})),/AUTHORIZATION_CANDIDATE_MISMATCH/);assert.equal(p.publishes,0);});
test("authorization shop mismatch performs no publish",async()=>{const r=new MemoryOperationLedgerRepository(),p=new Provider();await assert.rejects(()=>executeAuthorizedPublishTransaction(r,p,input({shopId:"OTHER"})),/AUTHORIZATION_SHOP_MISMATCH/);assert.equal(p.publishes,0);});
test("ambiguous provider response reconciles via read-only post-read",async()=>{const r=new MemoryOperationLedgerRepository(),p=new Provider();p.ambiguous=true;const x=await executeAuthorizedPublishTransaction(r,p,input());assert.equal(x.status,"RECONCILED");assert.equal(p.publishes,1);});
test("ambiguous with no receipt enters reconciliation and never republishes on replay",async()=>{const r=new MemoryOperationLedgerRepository();let publishes=0;const p:AuthorizedPublishProvider={async readDraft(){return read},async publish(){publishes++;throw new PublishAmbiguousResultError()},async readPublished(){return null}};const i=input();const a=await executeAuthorizedPublishTransaction(r,p,i);assert.equal(a.status,"RECONCILIATION_REQUIRED");const b=await executeAuthorizedPublishTransaction(r,p,{...i,now:"2026-09-05T09:01:00.000Z"});assert.equal(b.status,"RECONCILIATION_REQUIRED");assert.equal(publishes,1);});
test("later read-only reconciliation can close ambiguous operation without republish",async()=>{const r=new MemoryOperationLedgerRepository();let publishes=0,live:any=null;const p:AuthorizedPublishProvider={async readDraft(){return read},async publish(){publishes++;throw new PublishAmbiguousResultError()},async readPublished(){return live}};const i=input();await executeAuthorizedPublishTransaction(r,p,i);live={listingId:"LIVE-1",state:"active"};const x=await executeAuthorizedPublishTransaction(r,p,{...i,now:"2026-09-05T09:02:00.000Z"});assert.equal(x.status,"RECONCILED");assert.equal(publishes,1);});
test("successful operation replay never publishes twice",async()=>{const r=new MemoryOperationLedgerRepository(),p=new Provider(),i=input();await executeAuthorizedPublishTransaction(r,p,i);const x=await executeAuthorizedPublishTransaction(r,p,{...i,now:"2026-09-05T09:01:00.000Z"});assert.equal(x.status,"REPLAY");assert.equal(p.publishes,1);});
test("post-read must confirm active or published state",async()=>{const r=new MemoryOperationLedgerRepository();const p:AuthorizedPublishProvider={async readDraft(){return read},async publish(){return{listingId:"L",state:"draft"}},async readPublished(){return null}};await assert.rejects(()=>executeAuthorizedPublishTransaction(r,p,input()),/PUBLISHED_STATE_NOT_CONFIRMED/);});
test("same operation with changed transaction identity fails ledger idempotency",async()=>{const r=new MemoryOperationLedgerRepository(),p=new Provider(),i=input();await executeAuthorizedPublishTransaction(r,p,i);await assert.rejects(()=>executeAuthorizedPublishTransaction(r,p,{...i,expectedListingFingerprint:"b".repeat(64)}),/OPERATION_ID_PAYLOAD_MISMATCH/);});
