import assert from "node:assert/strict";import test from "node:test";import {MemoryOperationLedgerRepository} from "../lib/operation-ledger";import {executeReconciledWrite,ProviderAmbiguousResultError,type ReconciledWriteProvider,type ProviderReceipt} from "../lib/draft-upload-reconciliation";
const NOW="2026-09-05T08:30:00.000Z";
class Fake implements ReconciledWriteProvider{applies=0;store=new Map<string,ProviderReceipt>();ambiguous=false;fail=false;async apply(i:any){this.applies++;const r={providerResourceId:`RID-${i.operationId}`,kind:i.kind} as ProviderReceipt;this.store.set(i.operationId,r);if(this.ambiguous)throw new ProviderAmbiguousResultError();if(this.fail)throw new Error("PROVIDER_FAILED");return r;}async reconcile(i:any){return this.store.get(i.operationId)??null;}}
for(const kind of ["CREATE_DRAFT","UPLOAD_IMAGE","UPLOAD_FILE"] as const)test(`${kind} applies once and persists receipt`,async()=>{const repo=new MemoryOperationLedgerRepository(),p=new Fake();const x=await executeReconciledWrite(repo,p,{operationId:`OP-${kind}`,kind,payload:{x:1},now:NOW});assert.equal(x.status,"APPLIED");assert.equal(p.applies,1);});
test("same operation replay returns receipt without provider duplicate",async()=>{const repo=new MemoryOperationLedgerRepository(),p=new Fake(),input={operationId:"OP-1",kind:"CREATE_DRAFT" as const,payload:{x:1},now:NOW};await executeReconciledWrite(repo,p,input);const x=await executeReconciledWrite(repo,p,input);assert.equal(x.status,"REPLAY");assert.equal(p.applies,1);});
test("same operation ID different payload is rejected before provider",async()=>{const repo=new MemoryOperationLedgerRepository(),p=new Fake();await executeReconciledWrite(repo,p,{operationId:"OP-1",kind:"UPLOAD_IMAGE",payload:{x:1},now:NOW});await assert.rejects(()=>executeReconciledWrite(repo,p,{operationId:"OP-1",kind:"UPLOAD_IMAGE",payload:{x:2},now:NOW}),/OPERATION_ID_PAYLOAD_MISMATCH/);assert.equal(p.applies,1);});
test("timeout after provider success reconciles existing resource instead of duplicate",async()=>{const repo=new MemoryOperationLedgerRepository(),p=new Fake();p.ambiguous=true;const x=await executeReconciledWrite(repo,p,{operationId:"OP-A",kind:"UPLOAD_FILE",payload:{file:"A"},now:NOW});assert.equal(x.status,"RECONCILED");assert.equal(p.applies,1);assert.equal((x as any).receipt.providerResourceId,"RID-OP-A");});
test("ambiguous result with no read-back persists reconciliation recovery point",async()=>{const repo=new MemoryOperationLedgerRepository();const p:ReconciledWriteProvider={async apply(){throw new ProviderAmbiguousResultError()},async reconcile(){return null}};const x=await executeReconciledWrite(repo,p,{operationId:"OP-X",kind:"CREATE_DRAFT",payload:{},now:NOW});assert.equal(x.status,"RECONCILIATION_REQUIRED");assert.equal((await repo.load("OP-X"))?.recoveryPoint,"PROVIDER_READ_BACK");});
test("replay in reconciliation state checks provider without retrying apply",async()=>{const repo=new MemoryOperationLedgerRepository();let reconciles=0,applies=0;const p:ReconciledWriteProvider={async apply(i){applies++;throw new ProviderAmbiguousResultError()},async reconcile(i){reconciles++;return reconciles>1?{providerResourceId:"FOUND",kind:i.kind}:null}};const input={operationId:"OP-X",kind:"UPLOAD_IMAGE" as const,payload:{},now:NOW};await executeReconciledWrite(repo,p,input);const x=await executeReconciledWrite(repo,p,{...input,now:"2026-09-05T08:31:00.000Z"});assert.equal(x.status,"RECONCILED");assert.equal(applies,1);});
test("unresolved reconciliation replay remains blocked without another provider write",async()=>{const repo=new MemoryOperationLedgerRepository();let applies=0;const p:ReconciledWriteProvider={async apply(){applies++;throw new ProviderAmbiguousResultError()},async reconcile(){return null}};const input={operationId:"OP-BLOCKED",kind:"UPLOAD_IMAGE" as const,payload:{},now:NOW};await executeReconciledWrite(repo,p,input);const x=await executeReconciledWrite(repo,p,{...input,now:"2026-09-05T08:31:00.000Z"});assert.equal(x.status,"RECONCILIATION_REQUIRED");assert.equal(applies,1);});
test("definite provider failure marks FAILED and preserves same-ID recovery",async()=>{const repo=new MemoryOperationLedgerRepository(),p=new Fake();p.fail=true;await assert.rejects(()=>executeReconciledWrite(repo,p,{operationId:"OP-F",kind:"UPLOAD_IMAGE",payload:{},now:NOW}),/PROVIDER_FAILED/);assert.equal((await repo.load("OP-F"))?.status,"FAILED");assert.equal((await repo.load("OP-F"))?.recoveryPoint,"RETRY_SAME_OPERATION_ID");});
test("receipt metadata is detached from provider object",async()=>{const repo=new MemoryOperationLedgerRepository();const metadata={x:1};const p:ReconciledWriteProvider={async apply(i){return{providerResourceId:"R",kind:i.kind,metadata}},async reconcile(){return null}};const x=await executeReconciledWrite(repo,p,{operationId:"OP",kind:"UPLOAD_FILE",payload:{},now:NOW});metadata.x=2;assert.deepEqual((x as any).receipt.metadata,{x:1});});
