import assert from "node:assert/strict";import test from "node:test";import {buildProofRunTrace,propagateCorrelation,startCorrelation,validateCorrelationTrace,CORRELATION_STAGES,type CorrelationStage,type CorrelationEventInput} from "../lib/end-to-end-correlation";
const stages=CORRELATION_STAGES;function item(s:CorrelationStage,i:number):CorrelationEventInput{return{eventId:`EV-${i+1}`,aggregateId:"P1",eventType:`${s}_EVENT`,occurredAt:`2026-09-05T06:0${i}:00.000Z`,evidenceIds:[`E-${i+1}`]};}function inputs():Record<CorrelationStage,CorrelationEventInput>{return{ROUTER:item("ROUTER",0),FACTORY:item("FACTORY",1),GATE:item("GATE",2),PUBLISHER:item("PUBLISHER",3),GROWTH:item("GROWTH",4)};}
test("router starts one correlation without causation",()=>{const e=startCorrelation("CORR-1",inputs().ROUTER);assert.equal(e.correlationId,"CORR-1");assert.equal(e.causationId,undefined);assert.equal(e.aggregateType,"ROUTER");});
test("child propagation keeps correlation and points causation at parent",()=>{const r=startCorrelation("CORR-1",inputs().ROUTER);const f=propagateCorrelation(r,"FACTORY",inputs().FACTORY);assert.equal(f.correlationId,r.correlationId);assert.equal(f.causationId,r.eventId);});
test("proof run is traceable Router through Growth",()=>{const trace=buildProofRunTrace("CORR-PROOF",inputs());assert.deepEqual(trace.events.map(e=>e.aggregateType),["ROUTER","FACTORY","GATE","PUBLISHER","GROWTH"]);assert.deepEqual(trace.events.slice(1).map(e=>e.causationId),["EV-1","EV-2","EV-3","EV-4"]);});
test("all proof events share one correlation ID",()=>{const trace=buildProofRunTrace("CORR-PROOF",inputs());assert.equal(new Set(trace.events.map(e=>e.correlationId)).size,1);});
test("correlation mismatch fails closed",()=>{const trace=buildProofRunTrace("CORR-PROOF",inputs());trace.events[3].correlationId="OTHER";assert.throws(()=>validateCorrelationTrace(trace.events),/CORRELATION_ID_MISMATCH/);});
test("broken causation chain fails closed",()=>{const trace=buildProofRunTrace("CORR-PROOF",inputs());trace.events[2].causationId="WRONG";assert.throws(()=>validateCorrelationTrace(trace.events),/CAUSATION_CHAIN_MISMATCH/);});
test("wrong module order fails closed",()=>{const trace=buildProofRunTrace("CORR-PROOF",inputs());[trace.events[1],trace.events[2]]=[trace.events[2],trace.events[1]];assert.throws(()=>validateCorrelationTrace(trace.events),/CORRELATION_STAGE_ORDER_MISMATCH/);});
test("duplicate event IDs fail closed",()=>{const trace=buildProofRunTrace("CORR-PROOF",inputs());trace.events[4].eventId=trace.events[1].eventId;assert.throws(()=>validateCorrelationTrace(trace.events),/DUPLICATE_CORRELATION_EVENT_ID/);});
test("backwards event time fails closed",()=>{const trace=buildProofRunTrace("CORR-PROOF",inputs());trace.events[4].occurredAt="2026-09-05T05:00:00.000Z";assert.throws(()=>validateCorrelationTrace(trace.events),/CORRELATION_TIME_ORDER_MISMATCH/);});
test("proof builder is deterministic and read-only",()=>{const source=inputs();const before=structuredClone(source);const a=buildProofRunTrace("CORR-PROOF",source);const b=buildProofRunTrace("CORR-PROOF",structuredClone(source));assert.deepEqual(a,b);assert.deepEqual(source,before);});
