import assert from "node:assert/strict";import test from "node:test";import {classifyRouterIntent,routeIntentToStage} from "../lib/intent-stage-router";import type {CanonicalProductRecord} from "../lib/product-registry";
const SRC={driveFileId:"D",fileName:"catalog.xlsx",mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",accessMode:"READ_ONLY" as const};function record(state?:string):CanonicalProductRecord{return{schemaVersion:"1.0.0",productId:"P1",productVersion:"1",registryRevision:1,importedSource:SRC,rawLegacyCatalogStatus:"",migrationReview:{status:"CLEAR",reasons:[]},references:{listings:[],candidateIds:[],candidateFingerprints:[],passRecordIds:[],authorizationIds:[],evidenceIds:[]},...(state?{currentState:{value:state,evidenceReference:"E"}}:{})};}
test("Thai new-product intent maps to DISCOVERED",()=>{const r=routeIntentToStage({intentText:"หาสินค้าใหม่"});assert.equal(r.intent,"NEW_PRODUCT");assert.equal(r.nextExecutableStage,"DISCOVERED");});
test("continue maps to exactly one canonical next stage",()=>{const r=routeIntentToStage({intentText:"ทำต่อ",product:record("PRODUCT_TEST_PASS")});assert.equal(r.nextExecutableStage,"LISTING_BUILT");assert.equal(Array.isArray(r.nextExecutableStage),false);});
test("status is read-only but returns the same one next stage",()=>{const r=routeIntentToStage({intentText:"status",product:record("LISTING_BUILT")});assert.equal(r.command,"READ_STATUS");assert.equal(r.nextExecutableStage,"DRAFT_PERSISTED");assert.equal(r.execute,false);});
test("QC runs only when Final QC is actually next",()=>{const r=routeIntentToStage({intentText:"QC",product:record("PERSISTENCE_PASS")});assert.equal(r.command,"RUN_INDEPENDENT_QC");assert.equal(r.nextExecutableStage,"FINAL_QC_PASS");});
test("QC cannot shortcut earlier required stage",()=>{const r=routeIntentToStage({intentText:"ตรวจ QC",product:record("LISTING_BUILT")});assert.equal(r.nextExecutableStage,"DRAFT_PERSISTED");assert.equal(r.reason,"QC_NOT_NEXT_STAGE");});
test("patch maps to Patch Candidate workflow",()=>{const r=routeIntentToStage({intentText:"patch",product:record("MONITORING")});assert.equal(r.nextExecutableStage,"PATCH_CANDIDATE");assert.equal(r.command,"CREATE_PATCH_CANDIDATE");});
test("stop dispatches nothing",()=>{const r=routeIntentToStage({intentText:"หยุด"});assert.equal(r.nextExecutableStage,"STOP");assert.equal(r.execute,false);});
test("terminal state returns COMPLETE rather than replaying a stage",()=>{const r=routeIntentToStage({intentText:"continue",product:record("RETIRED")});assert.equal(r.nextExecutableStage,"COMPLETE");assert.equal(r.execute,false);});
test("migration ambiguity fails closed into one review stage",()=>{const p=record("UNKNOWN");const r=routeIntentToStage({intentText:"continue",product:p});assert.equal(r.nextExecutableStage,"MIGRATION_REVIEW_REQUIRED");assert.equal(r.execute,false);});
test("intent classifier supports Thai and English controls",()=>{assert.equal(classifyRouterIntent("สถานะ"),"STATUS");assert.equal(classifyRouterIntent("continue"),"CONTINUE");assert.equal(classifyRouterIntent("new product"),"NEW_PRODUCT");});
test("unknown intent fails closed and context-required intent needs product",()=>{assert.throws(()=>classifyRouterIntent("xyz"),/UNSUPPORTED_ROUTER_INTENT/);assert.throws(()=>routeIntentToStage({intentText:"continue"}),/PRODUCT_CONTEXT_REQUIRED/);});
