import assert from "node:assert/strict";import test from "node:test";import {CANDIDATE_MANIFEST_SCHEMA_VERSION,freezeCandidateManifest,type CandidateManifestInput} from "../lib/candidate-freeze";import {createPatchCandidateWorkflow} from "../lib/patch-candidate-workflow";
const T="2026-09-05T10:00:00.000Z";function source(){return freezeCandidateManifest({schemaVersion:CANDIDATE_MANIFEST_SCHEMA_VERSION,lineageId:"LINE-LIST",candidateVersion:1,candidateId:"LIST-V1",productId:"P1",candidateType:"LISTING",createdAt:T,frozenAt:T,artifactIds:["A1"],payload:{title:"Old",price:10}});}function patch(overrides:Partial<CandidateManifestInput>={}):CandidateManifestInput{return{schemaVersion:CANDIDATE_MANIFEST_SCHEMA_VERSION,lineageId:"LINE-PATCH",candidateVersion:1,candidateId:"PATCH-V1",productId:"P1",candidateType:"PATCH",createdAt:T,frozenAt:T,artifactIds:["A1"],payload:{title:"New",price:10},...overrides};}
test("listing-only patch creates immutable Patch Candidate",()=>{const r=createPatchCandidateWorkflow(source(),patch(),"LISTING_ONLY");assert.equal(r.patchCandidate.candidate.candidateType,"PATCH");assert.equal(Object.isFrozen(r),true);assert.equal(r.liveMutationAllowed,false);});
test("listing-only routes to Listing Intelligence and replays only listing/downstream gates",()=>{const r=createPatchCandidateWorkflow(source(),patch(),"LISTING_ONLY");assert.equal(r.affectedStage,"LISTING_INTELLIGENCE");assert.equal(r.nextGate,"LISTING_TEST");assert.deepEqual(r.mandatoryGateReplay,["LISTING_TEST","PERSISTENCE_VERIFY","INDEPENDENT_FINAL_QC"]);});
test("product-changing patch routes to Product Factory and replays every gate",()=>{const r=createPatchCandidateWorkflow(source(),patch({payload:{title:"New",productBytes:"changed"}}),"PRODUCT_CHANGE");assert.equal(r.affectedStage,"PRODUCT_FACTORY");assert.equal(r.nextGate,"PRODUCT_TEST");assert.deepEqual(r.mandatoryGateReplay,["PRODUCT_TEST","LISTING_TEST","PERSISTENCE_VERIFY","INDEPENDENT_FINAL_QC"]);});
test("every patch requires fresh production authorization",()=>{assert.equal(createPatchCandidateWorkflow(source(),patch(),"LISTING_ONLY").requiresNewAuthorization,true);});
test("candidate type must be PATCH",()=>{assert.throws(()=>createPatchCandidateWorkflow(source(),patch({candidateType:"LISTING"}),"LISTING_ONLY"),/PATCH_CANDIDATE_TYPE_REQUIRED/);});
test("patch cannot cross product identity",()=>{assert.throws(()=>createPatchCandidateWorkflow(source(),patch({productId:"P2"}),"LISTING_ONLY"),/PATCH_PRODUCT_ID_MISMATCH/);});
test("patch must use a new candidate ID",()=>{assert.throws(()=>createPatchCandidateWorkflow(source(),patch({candidateId:"LIST-V1"}),"LISTING_ONLY"),/PATCH_NEW_CANDIDATE_ID_REQUIRED/);});
test("no material change is rejected",()=>{assert.throws(()=>createPatchCandidateWorkflow(source(),patch({artifactIds:["A1"],payload:{title:"Old",price:10}}),"LISTING_ONLY"),/PATCH_HAS_NO_MATERIAL_CHANGE/);});
test("artifact-only product change is material and replays Product Test",()=>{const r=createPatchCandidateWorkflow(source(),patch({artifactIds:["A2"],payload:{title:"Old",price:10}}),"PRODUCT_CHANGE");assert.equal(r.nextGate,"PRODUCT_TEST");});
test("workflow preserves source candidate identity and does not mutate it",()=>{const s=source(),before=structuredClone(s);const r=createPatchCandidateWorkflow(s,patch(),"LISTING_ONLY");assert.equal(r.sourceCandidateId,"LIST-V1");assert.equal(r.sourceFingerprint,s.candidate.fingerprint);assert.deepEqual(s,before);});
