import assert from "node:assert/strict";
import test from "node:test";
import { exactPdRest003B01Body, handlePdRest003B01TitleTags, PD_REST_003_B01, verifyPdRest003B01ProtectedState } from "../lib/pd-rest-003-b01-title-tags";
import { hashOperationRequest, MemoryOperationLedgerRepository } from "../lib/operation-ledger";

const OLD_DESCRIPTION=`Make restaurant shifts easier to prepare, run and hand off with this pre-filled, editable 8-tab daily operations checklist toolkit for Excel, Google Sheets and print.\n\nQUICK FACTS\n• 1 ZIP containing the editable XLSX workbook + 4 PDFs\n• Workbook: 8 editable tabs\n• PDFs: A4, US Letter, Quick Start, and Read Me/License\n• Pre-filled operational tasks you can customize\n• Instant digital download — no physical item\n\nWORKBOOK TABS\nStart Here | Opening | Pre-Service | Closing | Prep & Temp | Cleaning | Handoff | Blank Checklist\n\nWHAT THIS HELPS YOU DO\n• Organize opening, pre-service and closing routines\n• Record prep and temperature checks in one place\n• Keep cleaning and shift handoff tasks visible\n• Assign responsibility, timing, status and notes\n• Print clean A4 or US Letter copies for the floor or kitchen\n\nHOW TO USE\nDownload and unzip the ZIP file first. Open the included XLSX workbook in Microsoft Excel, or upload it to Google Drive and open it with Google Sheets. Review the Start Here tab, replace sample tasks and limits with your approved procedures, then test the full workflow before daily use.\n\nIMPORTANT DOWNLOAD NOTE\nEtsy’s app does not currently download digital purchases. After checkout, sign in to Etsy.com using a mobile browser or computer, then go to Your account &gt; Purchases and reviews &gt; Download Files. A desktop or laptop is recommended for first-time spreadsheet setup.\n\nPLEASE NOTE\n• PDF files are print-ready and are not text-editable.\n• This is an operational planning tool, not HACCP, food-safety, legal, HR, tax, or regulatory advice.\n• Temperature limits, cleaning routines and operating procedures must be verified by the buyer for their equipment, menu and location.\n\nLICENSE\nSingle-business internal-use license. You may edit and print the files and share working copies with staff inside the purchasing business. You may not resell, redistribute, sublicense, upload publicly, or give the source files to another business.\n\nCREATION DISCLOSURE\nThis original digital toolkit was designed by PoonthaiDigital with AI-assisted drafting and visual support, then manually edited, tested, and quality-checked.\n\nNeed help after purchase? Message PoonthaiDigital through Etsy with the filename, device or app used, and a screenshot.`;
const OLD_TAGS=["restaurant checklist","opening checklist","closing checklist","restaurant manager","daily operations","manager checklist","kitchen checklist","shift checklist","restaurant excel","restaurant template","shift handoff","restaurant forms","food service"];
const TARGET_TAGS=["restaurant checklist","restaurant opening","restaurant closing","daily operations","restaurant manager","manager checklist","opening checklist","closing checklist","shift handoff","kitchen checklist","restaurant excel","restaurant forms","food temp log"];
const IMAGES=[[8496992722,1,3000,3000],[8488103428,2,2000,2000],[8488103480,3,2000,2000],[8488103438,4,2000,2000],[8536001153,5,2000,2000],[8536001075,6,2000,2000],[8488103510,7,2000,2000],[8536001073,8,2000,2000],[8488103512,9,2000,2000]];
const FILES=[[1509497122622,1,"Restaurant_Operations_A4.pdf",20782,"application/pdf"],[1509497122824,2,"Restaurant_Operations_US_Letter.pdf",20228,"application/pdf"],[1509497122832,3,"Restaurant_Read_Me_License.pdf",4219,"application/pdf"],[1511184698189,4,"Restaurant_Operations.zip",15018,"application/zip"],[1512037381313,5,"Restaurant_Quick_Start.pdf",31217,"application/pdf"]];
const prior={writes:process.env.PUBLISH_WRITES_ENABLED,token:process.env.ETSY_B01_WRITE_TOKEN,shop:process.env.ETSY_SHOP_ID,auth:process.env.ETSY_PD_REST_003_B01_AUTHORIZATION_ID,sha:process.env.ETSY_PD_REST_003_B01_REQUEST_SHA256,key:process.env.ETSY_API_KEY,secret:process.env.ETSY_SHARED_SECRET};
function restore(){const names={writes:"PUBLISH_WRITES_ENABLED",token:"ETSY_B01_WRITE_TOKEN",shop:"ETSY_SHOP_ID",auth:"ETSY_PD_REST_003_B01_AUTHORIZATION_ID",sha:"ETSY_PD_REST_003_B01_REQUEST_SHA256",key:"ETSY_API_KEY",secret:"ETSY_SHARED_SECRET"} as const;for(const[k,v]of Object.entries(prior)){const n=names[k as keyof typeof names];if(v===undefined)delete process.env[n];else process.env[n]=v;}}
test.afterEach(restore);
function response(v:unknown,status=200){return new Response(JSON.stringify(v),{status});}
function request(token?:string){return new Request("https://x",{method:"POST",headers:token?{"x-autodigitalpublisher-write-token":token}:{}});}
function configure(){process.env.PUBLISH_WRITES_ENABLED="true";process.env.ETSY_B01_WRITE_TOKEN="secret";process.env.ETSY_SHOP_ID=PD_REST_003_B01.shopId;process.env.ETSY_PD_REST_003_B01_AUTHORIZATION_ID="AUTH-REST-B01";process.env.ETSY_API_KEY="key";process.env.ETSY_SHARED_SECRET="secret";const body=exactPdRest003B01Body("AUTH-REST-B01");process.env.ETSY_PD_REST_003_B01_REQUEST_SHA256=hashOperationRequest(body);return body;}
function listing(target=false){return{listing_id:4561819638,shop_id:23582741,state:"active",title:target?PD_REST_003_B01.title:"Restaurant Opening & Closing Checklist | Daily Operations Template",description:OLD_DESCRIPTION,price:{amount:990,divisor:100,currency_code:"USD"},taxonomy_id:12476,quantity:998,who_made:"i_did",when_made:"2020_2026",listing_type:"download",tags:target?[...TARGET_TAGS]:[...OLD_TAGS]};}
function images(){return IMAGES.map(([listing_image_id,rank,full_width,full_height])=>({listing_image_id,rank,full_width,full_height}));}
function files(){return FILES.map(([listing_file_id,rank,filename,size_bytes,filetype])=>({listing_file_id,rank,filename,size_bytes,filetype}));}
function stateFetch(methods:string[],target:{value:boolean},patchBodies:string[]=[]){return async(url:URL|RequestInfo,init?:RequestInit)=>{const method=String(init?.method??"GET");methods.push(method);const u=String(url);if(method==="PATCH"){patchBodies.push(String(init?.body??""));target.value=true;return response({ok:true});}if(u.endsWith("/images"))return response({results:images()});if(u.endsWith("/properties"))return response({results:[]});if(u.endsWith("/files"))return response({results:files()});if(u.endsWith("/listings/4561819638"))return response(listing(target.value));return response({},404);};}

test("exact B01 contract and Etsy title punctuation are compliant",()=>{const b=exactPdRest003B01Body("AUTH-REST-B01");assert.equal(b.candidateFingerprint,"0aa5d93415e7f31686d6ef0fa68a591480e51a64063028816e9892cd7fc31339");assert.equal(b.buildFingerprint,"1258c5d6b1ea095b7b07d0b488562eafea2640e160994934d2d041e6f8f77605");assert.equal(b.acceptanceCriteriaSha256,"5aa823fda02987298dcffe7d2692252d9884f0325c4073f6eaf75a9acef42ba5");assert.deepEqual(Object.keys(b.patch),["title","tags"]);assert.equal((b.patch.title.match(/&/g)??[]).length,1);assert.deepEqual(b.patch.tags,TARGET_TAGS);assert.equal(b.patch.tags.length,13);});
test("request hash mismatch fails before Etsy access",async()=>{const b=configure();process.env.ETSY_PD_REST_003_B01_REQUEST_SHA256="f".repeat(64);let calls=0;const r=await handlePdRest003B01TitleTags(b,request("secret"),{getAccessToken:async()=>{calls++;return"x";},repository:new MemoryOperationLedgerRepository()});assert.equal(r.status,409);assert.equal(calls,0);});
test("zero-write verification uses four GETs",async()=>{process.env.ETSY_API_KEY="key";process.env.ETSY_SHARED_SECRET="secret";const methods:string[]=[];const target={value:false};const r=await verifyPdRest003B01ProtectedState({getAccessToken:async()=>"token",fetchImpl:stateFetch(methods,target)});const o=await r.json();assert.equal(r.status,200);assert.equal(o.status,"PROTECTED_STATE_MATCH");assert.equal(o.ETSY_WRITE_COUNT,0);assert.deepEqual(methods,["GET","GET","GET","GET"]);});
test("protected mismatch fails with zero PATCH",async()=>{const b=configure(),methods:string[]=[];const target={value:false};const base=stateFetch(methods,target);const f=async(url:URL|RequestInfo,init?:RequestInit)=>{const r=await base(url,init);if(String(url).endsWith("/listings/4561819638")&&String(init?.method??"GET")==="GET"){const x=listing(false);x.quantity=997;return response(x);}return r;};const r=await handlePdRest003B01TitleTags(b,request("secret"),{getAccessToken:async()=>"token",fetchImpl:f,repository:new MemoryOperationLedgerRepository()});assert.equal(r.status,409);assert.equal(methods.filter(x=>x==="PATCH").length,0);});
test("one-shot PATCH contains only title and tags",async()=>{const b=configure(),methods:string[]=[],target={value:false},patchBodies:string[]=[];const r=await handlePdRest003B01TitleTags(b,request("secret"),{getAccessToken:async()=>"token",fetchImpl:stateFetch(methods,target,patchBodies),repository:new MemoryOperationLedgerRepository()});const o=await r.json();assert.equal(r.status,200);assert.equal(o.status,"UPDATED_AND_VERIFIED");assert.equal(o.providerPatchCount,1);assert.equal(methods.filter(x=>x==="PATCH").length,1);const form=new URLSearchParams(patchBodies[0]);assert.deepEqual([...form.keys()],["title","tags"]);assert.equal(form.get("title"),PD_REST_003_B01.title);assert.equal(form.get("tags"),TARGET_TAGS.join(","));assert.equal(o.receipt.verified.protectedState,"PASS");});
test("provider 400 is terminal FAILED and exposes sanitized provider error",async()=>{const b=configure(),methods:string[]=[],target={value:false};const f=async(url:URL|RequestInfo,init?:RequestInit)=>{const method=String(init?.method??"GET");if(method==="PATCH"){methods.push(method);return response({error:"bad title",message:"invalid"},400);}return stateFetch(methods,target)(url,init);};const r=await handlePdRest003B01TitleTags(b,request("secret"),{getAccessToken:async()=>"token",fetchImpl:f,repository:new MemoryOperationLedgerRepository()});const o=await r.json();assert.equal(r.status,502);assert.equal(o.statusCode,400);assert.equal(o.providerPatchCount,1);assert.equal(o.providerError.error,"bad title");});
test("successful replay adds no provider PATCH",async()=>{const b=configure(),methods:string[]=[],target={value:false};const repo=new MemoryOperationLedgerRepository(),f=stateFetch(methods,target);const first=await handlePdRest003B01TitleTags(b,request("secret"),{getAccessToken:async()=>"token",fetchImpl:f,repository:repo});assert.equal(first.status,200);const n=methods.filter(x=>x==="PATCH").length;const second=await handlePdRest003B01TitleTags(b,request("secret"),{getAccessToken:async()=>"token",fetchImpl:f,repository:repo});const o=await second.json();assert.equal(o.status,"REPLAY");assert.equal(methods.filter(x=>x==="PATCH").length,n);});