import assert from "node:assert/strict";
import test from "node:test";
import { exactPdtBoba001B01DescriptionBody, handlePdtBoba001B01Description, PDT_BOBA_001_B01_DESCRIPTION, verifyPdtBoba001B01ProtectedState } from "../lib/pdt-boba-001-b01-description";
import { hashOperationRequest, MemoryOperationLedgerRepository } from "../lib/operation-ledger";

const prior = { writes: process.env.PUBLISH_WRITES_ENABLED, token: process.env.ETSY_B01_WRITE_TOKEN, shop: process.env.ETSY_SHOP_ID, auth: process.env.ETSY_BOBA_B01_DESCRIPTION_AUTHORIZATION_ID, sha: process.env.ETSY_BOBA_B01_DESCRIPTION_REQUEST_SHA256, key: process.env.ETSY_API_KEY, secret: process.env.ETSY_SHARED_SECRET };
function restore(){for(const [key,value] of Object.entries(prior)){const name={writes:"PUBLISH_WRITES_ENABLED",token:"ETSY_B01_WRITE_TOKEN",shop:"ETSY_SHOP_ID",auth:"ETSY_BOBA_B01_DESCRIPTION_AUTHORIZATION_ID",sha:"ETSY_BOBA_B01_DESCRIPTION_REQUEST_SHA256",key:"ETSY_API_KEY",secret:"ETSY_SHARED_SECRET"}[key as keyof typeof prior];if(value===undefined)delete process.env[name];else process.env[name]=value}}
function request(token?:string){return new Request("https://x",{method:"POST",headers:token?{"x-autodigitalpublisher-write-token":token}:{}})}
function response(v:unknown,status=200){return new Response(JSON.stringify(v),{status})}
function configure(){process.env.PUBLISH_WRITES_ENABLED="true";process.env.ETSY_B01_WRITE_TOKEN="secret";process.env.ETSY_SHOP_ID=PDT_BOBA_001_B01_DESCRIPTION.shopId;process.env.ETSY_BOBA_B01_DESCRIPTION_AUTHORIZATION_ID="AUTH-EXPLICIT-ONE-SHOT";process.env.ETSY_API_KEY="key";process.env.ETSY_SHARED_SECRET="secret";const body=exactPdtBoba001B01DescriptionBody("AUTH-EXPLICIT-ONE-SHOT");process.env.ETSY_BOBA_B01_DESCRIPTION_REQUEST_SHA256=hashOperationRequest(body);return body}

test.afterEach(restore);
test("fails closed without write enablement or write token before Etsy access",async()=>{delete process.env.PUBLISH_WRITES_ENABLED;let calls=0;const body=exactPdtBoba001B01DescriptionBody("A");const disabled=await handlePdtBoba001B01Description(body,request(),{getAccessToken:async()=>{calls++;return"x"}});assert.equal(disabled.status,403);process.env.PUBLISH_WRITES_ENABLED="true";delete process.env.ETSY_B01_WRITE_TOKEN;const unauth=await handlePdtBoba001B01Description(body,request(),{getAccessToken:async()=>{calls++;return"x"}});assert.equal(unauth.status,503);assert.equal(calls,0)});

test("exact contract is fingerprint-bound and description-only",()=>{const body=exactPdtBoba001B01DescriptionBody("AUTH-EXPLICIT-ONE-SHOT");assert.equal(body.candidateFingerprint,PDT_BOBA_001_B01_DESCRIPTION.candidateFingerprint);assert.equal(body.targetDescriptionSha256,PDT_BOBA_001_B01_DESCRIPTION.targetDescriptionSha256);assert.deepEqual(Object.keys(body.patch),["description"])});

test("request-hash mismatch fails before Etsy and ledger access",async()=>{const body=configure();process.env.ETSY_BOBA_B01_DESCRIPTION_REQUEST_SHA256="f".repeat(64);let calls=0;const r=await handlePdtBoba001B01Description(body,request("secret"),{getAccessToken:async()=>{calls++;return"x"},repository:new MemoryOperationLedgerRepository()});assert.equal(r.status,409);assert.equal(calls,0)});

test("fresh protected-state mismatch performs four GETs and zero Etsy writes",async()=>{const body=configure(),methods:string[]=[];const fetchImpl=async(_u:URL|RequestInfo,init?:RequestInit)=>{methods.push(String(init?.method));return response(String(_u).endsWith("/images")||String(_u).endsWith("/properties")||String(_u).endsWith("/files")?{results:[]}:{shop_id:23582741,state:"active"})};const r=await handlePdtBoba001B01Description(body,request("secret"),{getAccessToken:async()=>"token",fetchImpl,repository:new MemoryOperationLedgerRepository()});assert.equal(r.status,409);assert.deepEqual(methods,["GET","GET","GET","GET"])});

test("zero-write staging verification never accepts authorization and never sends a non-GET",async()=>{process.env.ETSY_API_KEY="key";process.env.ETSY_SHARED_SECRET="secret";const methods:string[]=[];const r=await verifyPdtBoba001B01ProtectedState({getAccessToken:async()=>"token",fetchImpl:async(u,init)=>{methods.push(String(init?.method));return response(String(u).includes("/listings/4560696421/")?{results:[]}:{shop_id:23582741,state:"active"})}});const out=await r.json();assert.equal(r.status,409);assert.equal(out.ETSY_WRITE_COUNT,0);assert.ok(methods.every(x=>x==="GET"))});
