import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import test from "node:test";
import {
  exactPdtBoba001B01BuyerFilesBody,
  handlePdtBoba001B01BuyerFiles,
  PDT_BOBA_001_B01_BUYER_FILES,
  PDT_BOBA_001_B01_BUYER_FILE_SHA_EVIDENCE_GAP,
  verifyPdtBoba001B01BuyerFileAsset,
  verifyPdtBoba001B01BuyerFilesProtectedState,
  type PdtBoba001B01BuyerFileTarget
} from "../lib/pdt-boba-001-b01-buyer-files";
import { PDT_BOBA_001_B01_DESCRIPTION } from "../lib/pdt-boba-001-b01-description";
import { beginOperation, hashOperationRequest, MemoryOperationLedgerRepository } from "../lib/operation-ledger";

const AUTH="TEST-NEW-EXACT-AUTHORIZATION";
const TAGS=["bubble tea business","boba shop toolkit","boba operations","boba shop sop","cafe opening closing","daily prep log","stock waste tracker","shift handoff log","tea cafe template","milktea inventory","cafe cleaning sheet","drink shop checklist","google sheets boba"];
const GALLERY=[[8547319609,1,2000,1600],[8547319665,2,2000,1600],[8547319731,3,1600,900],[8547319783,4,1600,900],[8547319831,5,1600,900],[8547319873,6,1600,900],[8499440812,7,1600,900],[8499440860,8,1600,900],[8499440896,9,1600,900],[8547320067,10,1600,900],[8547320117,11,1600,900],[8499441032,12,1600,900]] as const;
const INITIAL=[[1509032655604,1,"PoonthaiDigital_Boba_Checklist_A4.pdf",17459,"application/pdf"],[1509032655658,2,"PoonthaiDigital_Boba_Checklist_US_Letter.pdf",16632,"application/pdf"],[1509891952828,3,"Boba_Read_Me_License.pdf",4620,"application/pdf"],[1509891952826,4,"Boba_Quick_Start.pdf",4564,"application/pdf"],[1509980398204,5,"PoonthaiDigital_Boba_Shop_Operations_Tracker.zip",22370,"application/zip"]] as const;
const core=(over:Record<string,unknown>={})=>({listing_id:4560696421,shop_id:23582741,state:"active",title:"Boba Shop Operations Toolkit, Cafe Daily SOP, Checklist, Excel Google Sheets Template (Digital Download)",description:PDT_BOBA_001_B01_DESCRIPTION.description,price:{amount:1290,divisor:100,currency_code:"USD"},taxonomy_id:12476,quantity:999,who_made:"i_did",when_made:"2020_2026",listing_type:"download",tags:[...TAGS],return_policy_id:1,file_data:"4 PDF, 1 ZIP",...over});
const imgs=()=>GALLERY.map(([listing_image_id,rank,full_width,full_height])=>({listing_image_id,rank,full_width,full_height}));
const initFiles=():Array<Record<string,unknown>>=>INITIAL.map(([listing_file_id,rank,filename,size_bytes,filetype])=>({listing_file_id,rank,filename,size_bytes,filetype}));
const vids=()=>[{video_id:9001,height:1080,width:1080,thumbnail_url:"t",video_url:"v",video_state:"active"}];
const req=(body:Record<string,unknown>)=>new Request("https://example.test",{method:"POST",headers:{"x-autodigitalpublisher-write-token":"test-write-token","content-type":"application/json"},body:JSON.stringify(body)});
const js=(r:Response)=>r.json() as Promise<Record<string,unknown>>;
function auth(body=exactPdtBoba001B01BuyerFilesBody(AUTH)){process.env.PUBLISH_WRITES_ENABLED="true";process.env.ETSY_B01_WRITE_TOKEN="test-write-token";process.env.ETSY_SHOP_ID="23582741";process.env.ETSY_API_KEY="k";process.env.ETSY_SHARED_SECRET="s";process.env.ETSY_BOBA_B01_BUYER_FILES_AUTHORIZATION_ID=AUTH;process.env.ETSY_BOBA_B01_BUYER_FILES_REQUEST_SHA256=hashOperationRequest(body);}
type Opt={listing?:Record<string,unknown>;files?:Array<Record<string,unknown>>;fail?:number;failStatus?:number;throwAt?:number;driftAt?:number};
function provider(o:Opt={}){
  let fs:Array<Record<string,unknown>>=structuredClone(o.files??initFiles()),c=core(o.listing),writes=0,fileGets=0;
  const methods:string[]=[],deleteUrls:string[]=[];
  const fetchImpl=(async(input:string|URL|Request,init?:RequestInit)=>{
    const url=String(input),m=init?.method??"GET";methods.push(m);
    if(m==="DELETE"){
      writes++;deleteUrls.push(url);
      if(o.throwAt===writes)throw new Error("ambiguous");
      if(o.fail===writes)return Response.json({error:"rejected"},{status:o.failStatus??400});
      const id=Number(url.split("/").at(-1));
      assert.ok(PDT_BOBA_001_B01_BUYER_FILES.targets.some(target=>target.currentListingFileId===id));
      fs=fs.filter(file=>Number(file.listing_file_id)!==id).sort((a,b)=>Number(a.rank)-Number(b.rank)).map((file,index)=>({...file,rank:index+1}));
      if(o.driftAt===writes)c=core({title:"drift"});
      return new Response(null,{status:204});
    }
    if(m==="POST"){
      writes++;
      if(o.throwAt===writes)throw new Error("ambiguous");
      if(o.fail===writes)return Response.json({error:"rejected"},{status:o.failStatus??400});
      if(fs.length>=5)return Response.json({error:"maximum files reached"},{status:400});
      const form=init?.body;if(!(form instanceof FormData))throw new Error("form");
      const rank=Number(form.get("rank")),target=PDT_BOBA_001_B01_BUYER_FILES.targets.find(x=>x.slot===rank);assert.ok(target);
      assert.equal(String(form.get("name")),target.fileName);const f=form.get("file");assert.ok(f instanceof File);assert.equal(f.name,target.fileName);
      fs=fs.map(file=>Number(file.rank)>=rank?{...file,rank:Number(file.rank)+1}:file);
      const id=1600000000000+rank;fs.push({listing_file_id:id,listing_id:4560696421,rank,filename:target.fileName,size_bytes:target.targetSizeBytes,filetype:target.mimeType});fs.sort((a,b)=>Number(a.rank)-Number(b.rank));
      if(o.driftAt===writes)c=core({title:"drift"});
      return Response.json({listing_file_id:id,listing_id:4560696421,rank,filename:target.fileName,size_bytes:target.targetSizeBytes,filetype:target.mimeType},{status:201});
    }
    if(url.endsWith("/listings/4560696421"))return Response.json(c);
    if(url.endsWith("/images"))return Response.json({results:imgs()});
    if(url.endsWith("/properties"))return Response.json({results:[]});
    if(url.endsWith("/files")){fileGets++;return Response.json({count:fs.length,results:structuredClone(fs)});}
    if(url.endsWith("/videos"))return Response.json({count:1,results:vids()});
    return new Response("{}",{status:404});
  }) as typeof fetch;
  return{fetchImpl,methods,deleteUrls,writes:()=>writes,fileGets:()=>fileGets,files:()=>fs};
}
function rt(p:ReturnType<typeof provider>,repository=new MemoryOperationLedgerRepository()){return{repository,getAccessToken:async()=>"token",loadAsset:async(t:PdtBoba001B01BuyerFileTarget)=>Buffer.alloc(t.targetSizeBytes,t.slot),verifyAsset:()=>true,clearAsset:async()=>undefined,fetchImpl:p.fetchImpl,now:()=>"2026-09-12T04:00:00.000Z"};}

test("exact frozen identity and two targets",()=>{const c=PDT_BOBA_001_B01_BUYER_FILES;assert.equal(c.operationId,"PDT-BOBA-001-B01-BUYER-FILES-001");assert.equal(c.operation,"REPLACE_EXACT_TWO_DIGITAL_BUYER_FILES_ONLY");assert.equal(c.candidateId,"ETSY-FULL-REBUILD-PDT-BOBA-001-V1-2026-09-12-B");assert.equal(c.candidateFingerprint,"85dae17bac2e772771fb4fa825fd66af617a7833d6dd06c7bab4873c2dbd1056");assert.equal(c.buildId,"ETSY-FULL-REBUILD-PDT-BOBA-001-BUILD-20260912-B01");assert.equal(c.buildFingerprint,"6128efc19ba774c0ba4e17d4f854bdb38ac1d41ed5a672ff9fea47066810b3fb");assert.equal(c.buildFreezeSha256,"9edc333f09e04a45440ab54b53894f9422b6b33d9b7be9d1b06444a9b5b981c9");assert.equal(c.acceptanceCriteriaId,"ETSY-AC-PDT-BOBA-001-FULL-REBUILD-B01-V1");assert.equal(c.acceptanceCriteriaSha256,"75abe1d42b6f69698e2e4a0070921fe7127d57203cad0f1b7538cfd55a7829e1");assert.deepEqual(c.targets.map(x=>[x.slot,x.sha256,x.targetSizeBytes]),[[4,"8e31ebfcefba49a6705c8690422ba9188e757c78b0c36c59e119afb70169c76c",5305],[5,"f57f510f416ecfa244d3b351e945cbe7856e8f364dff0a457012f1b6ebc42d78",22264]]);});
test("asset SHA size filename validation",()=>{const b=Buffer.from("bytes"),base=PDT_BOBA_001_B01_BUYER_FILES.targets[0],t={...base,fileName:"x.pdf",targetSizeBytes:b.length,sha256:createHash("sha256").update(b).digest("hex")} as unknown as PdtBoba001B01BuyerFileTarget;assert.equal(verifyPdtBoba001B01BuyerFileAsset(b,t),true);assert.equal(verifyPdtBoba001B01BuyerFileAsset(Buffer.concat([b,Buffer.from("x")]),t),false);assert.equal(verifyPdtBoba001B01BuyerFileAsset(Buffer.alloc(b.length),t),false);assert.equal(verifyPdtBoba001B01BuyerFileAsset(b,t,"wrong.pdf" as never),false);});
test("registered in existing operation and asset routes",()=>{const a=readFileSync(new URL("../app/api/internal/etsy/authorized-operation/route.ts",import.meta.url),"utf8"),b=readFileSync(new URL("../app/api/internal/etsy/authorized-operation/asset-chunk/route.ts",import.meta.url),"utf8");assert.match(a,/PDT_BOBA_001_B01_BUYER_FILES\.operationId/);assert.match(a,/AUTHORIZED_ETSY_OPERATION_NOT_REGISTERED/);assert.match(b,/PDT_BOBA_001_B01_BUYER_FILES\.targets/);assert.match(b,/AUTHORIZED_ETSY_ASSET_NOT_REGISTERED/);});
test("read-only verifier matches and writes zero",async()=>{process.env.ETSY_API_KEY="k";process.env.ETSY_SHARED_SECRET="s";const p=provider(),r=await verifyPdtBoba001B01BuyerFilesProtectedState({getAccessToken:async()=>"token",fetchImpl:p.fetchImpl}),x=await js(r);assert.equal(r.status,200);assert.equal(x.status,"PROTECTED_STATE_MATCH");assert.equal(x.ETSY_WRITE_COUNT,0);assert.equal(p.writes(),0);});
test("protected or target mismatch zero-write",async()=>{const body=exactPdtBoba001B01BuyerFilesBody(AUTH);auth(body);let p=provider({listing:{title:"drift"}}),r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p));assert.equal(r.status,409);assert.equal((await js(r)).ETSY_WRITE_COUNT,0);assert.equal(p.writes(),0);const f=initFiles();f[3]={...f[3],size_bytes:9999};p=provider({files:f});r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p));assert.equal(r.status,409);assert.equal(p.writes(),0);});
test("same replay zero-write and different payload rejected",async()=>{const body=exactPdtBoba001B01BuyerFilesBody(AUTH);auth(body);const repo=new MemoryOperationLedgerRepository(),p=provider(),runtime=rt(p,repo);let r=await handlePdtBoba001B01BuyerFiles(body,req(body),runtime);assert.equal(r.status,200);const n=p.writes();r=await handlePdtBoba001B01BuyerFiles(body,req(body),runtime);assert.equal((await js(r)).ETSY_WRITE_COUNT,0);assert.equal(p.writes(),n);const badRepo=new MemoryOperationLedgerRepository();await beginOperation(badRepo,PDT_BOBA_001_B01_BUYER_FILES.operationId,{different:true},"2026-09-12T03:00:00.000Z");const q=provider();r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(q,badRepo));assert.equal((await js(r)).error,"OPERATION_ID_PAYLOAD_MISMATCH");assert.equal(q.writes(),0);});
test("deterministic delete rejection is FAILED and never blindly retried",async()=>{const body=exactPdtBoba001B01BuyerFilesBody(AUTH);auth(body);const repo=new MemoryOperationLedgerRepository(),p=provider({fail:1,failStatus:400});let r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p,repo));assert.equal(r.status,502);{const x=await js(r);assert.equal(x.ETSY_WRITE_COUNT,0);assert.equal(x.ETSY_WRITE_ATTEMPT_COUNT,1);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"CONFIRMED");}assert.equal((await repo.load(PDT_BOBA_001_B01_BUYER_FILES.operationId))?.status,"FAILED");r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p,repo));assert.match(String((await js(r)).error),/FAILED_DO_NOT_RETRY/);assert.equal(p.writes(),1);});
test("all four provider mutation rejection points count only confirmed mutations",async()=>{const confirmed=[0,1,2,3];for(const fail of [1,2,3,4]){const body=exactPdtBoba001B01BuyerFilesBody(AUTH);auth(body);const repo=new MemoryOperationLedgerRepository(),p=provider({fail,failStatus:400}),r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p,repo)),x=await js(r);assert.equal(x.ETSY_WRITE_COUNT,confirmed[fail-1]);assert.equal(x.ETSY_WRITE_ATTEMPT_COUNT,fail);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"CONFIRMED");assert.equal(p.writes(),fail);const status=(await repo.load(PDT_BOBA_001_B01_BUYER_FILES.operationId))?.status;assert.equal(status,fail===1||fail===3?"FAILED":"RECONCILIATION_REQUIRED");}}
);
test("all four ambiguous mutation points preserve last confirmed count and require reconciliation",async()=>{const confirmed=[0,1,2,3];for(const throwAt of [1,2,3,4]){const body=exactPdtBoba001B01BuyerFilesBody(AUTH);auth(body);const repo=new MemoryOperationLedgerRepository(),p=provider({throwAt});let r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p,repo));assert.equal(r.status,202);let x=await js(r);assert.equal(x.ETSY_WRITE_COUNT,confirmed[throwAt-1]);assert.equal(x.ETSY_WRITE_ATTEMPT_COUNT,throwAt);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"UNRESOLVED_REQUIRES_RECONCILIATION");assert.equal((await repo.load(PDT_BOBA_001_B01_BUYER_FILES.operationId))?.status,"RECONCILIATION_REQUIRED");r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p,repo));assert.equal(r.status,202);x=await js(r);assert.equal(x.ETSY_WRITE_COUNT,0);assert.equal(p.writes(),throwAt);}}
);
test("protected slots1-3 and non-file fields remain unchanged",async()=>{const body=exactPdtBoba001B01BuyerFilesBody(AUTH);auth(body);const p=provider({driftAt:1}),r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p));assert.equal(r.status,202);{const x=await js(r);assert.equal(x.ETSY_WRITE_COUNT,1);assert.equal(x.ETSY_WRITE_ATTEMPT_COUNT,1);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"CONFIRMED");}assert.deepEqual(p.files().slice(0,3).map(x=>[x.listing_file_id,x.rank,x.filename,x.size_bytes,x.filetype]),INITIAL.slice(0,3));assert.equal(p.methods.includes("PATCH"),false);assert.deepEqual(p.deleteUrls,["https://api.etsy.com/v3/application/shops/23582741/listings/4560696421/files/1509891952826"]);});
test("pending replay is fail-closed and never resumes provider mutation automatically",async()=>{const body=exactPdtBoba001B01BuyerFilesBody(AUTH);auth(body);const deleted=initFiles().filter(file=>Number(file.listing_file_id)!==1509891952826).map((file,index)=>({...file,rank:index+1})),p=provider({files:deleted}),repo=new MemoryOperationLedgerRepository();const begun=await beginOperation(repo,PDT_BOBA_001_B01_BUYER_FILES.operationId,body,"2026-09-12T03:00:00.000Z");assert.equal(begun.status,"STARTED");await repo.save({...begun.record,receipt:{completedTargets:[],protectedVideoSnapshot:vids(),ETSY_WRITE_COUNT:1,ETSY_WRITE_ATTEMPT_COUNT:1,ETSY_WRITE_COUNT_STATUS:"CONFIRMED"},recoveryPoint:"TARGET_4_DELETE_VERIFIED"});const r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p,repo)),x=await js(r);assert.equal(r.status,202);assert.equal(x.ETSY_WRITE_COUNT,1);assert.equal(x.ETSY_WRITE_ATTEMPT_COUNT,1);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"UNRESOLVED_REQUIRES_RECONCILIATION");assert.equal(p.writes(),0);assert.equal((await repo.load(PDT_BOBA_001_B01_BUYER_FILES.operationId))?.status,"RECONCILIATION_REQUIRED");});
test("pending state that may be ahead of ledger never repeats delete or upload",async()=>{const body=exactPdtBoba001B01BuyerFilesBody(AUTH);auth(body);const replaced=initFiles().map(file=>Number(file.listing_file_id)===1509891952826?{listing_file_id:1600000000004,rank:4,filename:"Boba_Quick_Start.pdf",size_bytes:5305,filetype:"application/pdf"}:file),p=provider({files:replaced}),repo=new MemoryOperationLedgerRepository();const begun=await beginOperation(repo,PDT_BOBA_001_B01_BUYER_FILES.operationId,body,"2026-09-12T03:00:00.000Z");assert.equal(begun.status,"STARTED");await repo.save({...begun.record,receipt:{completedTargets:[],inFlightTarget:{slot:4,phase:"DELETE_VERIFIED",deletedListingFileId:"1509891952826",expectedSha256:PDT_BOBA_001_B01_BUYER_FILES.targets[0].sha256},protectedVideoSnapshot:vids(),ETSY_WRITE_COUNT:1,ETSY_WRITE_ATTEMPT_COUNT:2,ETSY_WRITE_COUNT_STATUS:"UNRESOLVED_REQUIRES_RECONCILIATION"},recoveryPoint:"TARGET_4_DELETE_VERIFIED"});const r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p,repo)),x=await js(r);assert.equal(r.status,202);assert.equal(x.ETSY_WRITE_COUNT,1);assert.equal(x.ETSY_WRITE_ATTEMPT_COUNT,2);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"UNRESOLVED_REQUIRES_RECONCILIATION");assert.equal(p.writes(),0);});
test("success uses exact delete+upload model, four writes, and provider SHA gap",async()=>{const body=exactPdtBoba001B01BuyerFilesBody(AUTH);auth(body);const repo=new MemoryOperationLedgerRepository(),p=provider(),r=await handlePdtBoba001B01BuyerFiles(body,req(body),rt(p,repo)),x=await js(r);assert.equal(r.status,200);assert.equal(x.status,"UPDATED_AND_VERIFIED");assert.equal(x.ETSY_WRITE_COUNT,4);assert.equal(x.ETSY_WRITE_ATTEMPT_COUNT,4);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"CONFIRMED");assert.equal(p.methods.filter(m=>m==="DELETE").length,2);assert.equal(p.methods.filter(m=>m==="POST").length,2);assert.ok(p.fileGets()>=6);assert.deepEqual(p.deleteUrls.map(url=>url.split("/").at(-1)),["1509891952826","1509980398204"]);assert.deepEqual(p.files().slice(0,3).map(f=>[f.listing_file_id,f.rank,f.filename,f.size_bytes,f.filetype]),INITIAL.slice(0,3));assert.equal(p.files()[3].size_bytes,5305);assert.equal(p.files()[4].size_bytes,22264);const gaps=(x.receipt as Record<string,unknown>).evidenceGaps as Record<string,unknown>;assert.equal(gaps.providerBuyerFileSha256,PDT_BOBA_001_B01_BUYER_FILE_SHA_EVIDENCE_GAP);assert.equal((await repo.load(PDT_BOBA_001_B01_BUYER_FILES.operationId))?.status,"SUCCEEDED");});
