import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { hashOperationRequest, MemoryOperationLedgerRepository } from "../lib/operation-ledger";
import { PDT_BOBA_001_B01_DESCRIPTION } from "../lib/pdt-boba-001-b01-description";
import {
  exactPdtBoba001B01ZipUploadRecovery002Body,
  handlePdtBoba001B01ZipUploadRecovery002,
  PDT_BOBA_001_B01_ZIP_UPLOAD_RECOVERY_002,
  verifyPdtBoba001B01ZipUploadRecovery002ProtectedState
} from "../lib/pdt-boba-001-b01-buyer-files-zip-upload-recovery-002";

const AUTH="PDT-BOBA-001-B01-ZIP-UPLOAD-RECOVERY-AUTH-20260914-06";
const REQUEST_SHA="b9b3f36a3820b271d9b764c96889cbac232fe66b3de9a82f75faa9370fc63a2b";
const TAGS=["bubble tea business","boba shop toolkit","boba operations","boba shop sop","cafe opening closing","daily prep log","stock waste tracker","shift handoff log","tea cafe template","milktea inventory","cafe cleaning sheet","drink shop checklist","google sheets boba"];
const GALLERY=[[8547319609,1,2000,1600],[8547319665,2,2000,1600],[8547319731,3,1600,900],[8547319783,4,1600,900],[8547319831,5,1600,900],[8547319873,6,1600,900],[8499440812,7,1600,900],[8499440860,8,1600,900],[8499440896,9,1600,900],[8547320067,10,1600,900],[8547320117,11,1600,900],[8499441032,12,1600,900]];
const files4=()=>[
 {listing_file_id:1509032655604,rank:1,filename:"PoonthaiDigital_Boba_Checklist_A4.pdf",size_bytes:17459,filetype:"application/pdf"},
 {listing_file_id:1509032655658,rank:2,filename:"PoonthaiDigital_Boba_Checklist_US_Letter.pdf",size_bytes:16632,filetype:"application/pdf"},
 {listing_file_id:1509891952828,rank:3,filename:"Boba_Read_Me_License.pdf",size_bytes:4620,filetype:"application/pdf"},
 {listing_file_id:1515492140861,rank:4,filename:"Boba_Quick_Start.pdf",size_bytes:5305,filetype:"application/pdf"}
];
const core=(fileData="4 PDF")=>({listing_id:4560696421,shop_id:23582741,state:"active",title:"Boba Shop Operations Toolkit, Cafe Daily SOP, Checklist, Excel Google Sheets Template (Digital Download)",description:PDT_BOBA_001_B01_DESCRIPTION.description,price:{amount:1290,divisor:100,currency_code:"USD"},taxonomy_id:12476,quantity:999,who_made:"i_did",when_made:"2020_2026",listing_type:"download",tags:[...TAGS],return_policy_id:1,file_data:fileData});
const imgs=()=>GALLERY.map(([listing_image_id,rank,full_width,full_height])=>({listing_image_id,rank,full_width,full_height}));
const vids=()=>[{video_id:841193954,height:1280,width:1600,thumbnail_url:"t",video_url:"v",video_state:"active"}];
type Opt={throwPost?:boolean;postStatus?:number;startWithZip?:boolean};
function provider(o:Opt={}){let files=files4(),listing=core(),writes=0;const methods:string[]=[];if(o.startWithZip){files.push({listing_file_id:999,rank:5,filename:"PoonthaiDigital_Boba_Shop_Operations_Tracker.zip",size_bytes:22370,filetype:"application/zip"});listing=core("4 PDF, 1 ZIP");}const fetchImpl=(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input),method=init?.method??"GET";methods.push(method);if(method==="DELETE")throw new Error("DELETE forbidden in upload-only recovery");if(method==="POST"){writes++;if(o.throwPost)throw new Error("ambiguous");if(o.postStatus&&o.postStatus!==201)return Response.json({error:"rejected"},{status:o.postStatus});const form=init?.body;assert.ok(form instanceof FormData);assert.equal(String(form.get("rank")),"5");files.push({listing_file_id:1700000000005,rank:5,filename:"PoonthaiDigital_Boba_Shop_Operations_Tracker.zip",size_bytes:22264,filetype:"application/zip"});listing=core("4 PDF, 1 ZIP");return Response.json({listing_file_id:1700000000005},{status:201});}if(url.endsWith("/listings/4560696421"))return Response.json(listing);if(url.endsWith("/images"))return Response.json({results:imgs()});if(url.endsWith("/properties"))return Response.json({results:[]});if(url.endsWith("/files"))return Response.json({results:structuredClone(files)});if(url.endsWith("/videos"))return Response.json({results:vids()});return new Response("{}",{status:404});}) as typeof fetch;return{fetchImpl,writes:()=>writes,methods,files:()=>files};}
async function repo(){const r=new MemoryOperationLedgerRepository();await r.save({schemaVersion:"1.0.0",operationId:"PDT-BOBA-001-B01-BUYER-FILES-ZIP-RECOVERY-003",requestHash:"42db6f28c0f2e130a64830632cdddb4a5dc1cdd40e6cd60ebe23428c9b78d789",attempts:2,status:"RECONCILIATION_REQUIRED",recoveryPoint:"ZIP_DELETE_READBACK_FAILED",receipt:{providerStatus:204,ETSY_WRITE_COUNT:0,ETSY_WRITE_ATTEMPT_COUNT:1,ETSY_WRITE_COUNT_STATUS:"UNRESOLVED_REQUIRES_RECONCILIATION"},createdAt:"2026-09-14T00:51:39.808Z",updatedAt:"2026-09-14T00:51:40.579Z"});return r;}
function auth(body=exactPdtBoba001B01ZipUploadRecovery002Body(AUTH)){process.env.PUBLISH_WRITES_ENABLED="true";process.env.ETSY_B01_WRITE_TOKEN="test-write-token";process.env.ETSY_SHOP_ID="23582741";process.env.ETSY_API_KEY="k";process.env.ETSY_SHARED_SECRET="s";process.env.ETSY_BOBA_B01_ZIP_UPLOAD_RECOVERY_002_AUTHORIZATION_ID=AUTH;process.env.ETSY_BOBA_B01_ZIP_UPLOAD_RECOVERY_002_REQUEST_SHA256=hashOperationRequest(body);}
const req=()=>new Request("https://example.test",{method:"POST",headers:{"x-autodigitalpublisher-write-token":"test-write-token"}});
const js=(r:Response)=>r.json() as Promise<Record<string,unknown>>;
const runtime=(p:ReturnType<typeof provider>,r:MemoryOperationLedgerRepository)=>({repository:r,parentRepository:r,getAccessToken:async()=>"token",loadAsset:async()=>Buffer.alloc(22264),verifyAsset:()=>true,fetchImpl:p.fetchImpl,now:()=>"2026-09-14T01:00:00.000Z"});

test("004 identity is upload-only and request hash is frozen",()=>{const x=PDT_BOBA_001_B01_ZIP_UPLOAD_RECOVERY_002;assert.equal(x.operation,"RECOVER_UPLOAD_MISSING_ZIP_ONLY");assert.equal(x.operationId,"PDT-BOBA-001-B01-BUYER-FILES-ZIP-UPLOAD-RECOVERY-004");assert.equal(hashOperationRequest(exactPdtBoba001B01ZipUploadRecovery002Body(AUTH)),REQUEST_SHA);const source=readFileSync(new URL("../lib/pdt-boba-001-b01-buyer-files-zip-upload-recovery-002.ts",import.meta.url),"utf8");assert.doesNotMatch(source,/method:\s*["']DELETE["']/);});
test("dedicated OIDC route and workflow are registered",()=>{const route=readFileSync(new URL("../app/api/internal/etsy/pdt-boba-001/b01/zip-upload-recovery-004/route.ts",import.meta.url),"utf8"),wf=readFileSync(new URL("../.github/workflows/execute-boba-zip-upload-recovery-004.yml",import.meta.url),"utf8");assert.match(route,/PDT_BOBA_001_B01_ZIP_UPLOAD_RECOVERY_002/);assert.match(wf,/zip-upload-recovery-004/);});
test("fresh verifier accepts exact four-file post-delete state with zero writes",async()=>{auth();const r=await repo(),p=provider(),res=await verifyPdtBoba001B01ZipUploadRecovery002ProtectedState({repository:r,getAccessToken:async()=>"token",fetchImpl:p.fetchImpl}),x=await js(res);assert.equal(res.status,200);assert.equal(x.status,"PROTECTED_STATE_MATCH");assert.equal(x.currentBuyerFileCount,4);assert.equal(p.writes(),0);});
test("verifier rejects if a ZIP is already present",async()=>{auth();const r=await repo(),p=provider({startWithZip:true}),res=await verifyPdtBoba001B01ZipUploadRecovery002ProtectedState({repository:r,getAccessToken:async()=>"token",fetchImpl:p.fetchImpl});assert.equal(res.status,409);assert.equal(p.writes(),0);});
test("successful recovery performs POST only once and restores exact slot five",async()=>{const body=exactPdtBoba001B01ZipUploadRecovery002Body(AUTH);auth(body);const r=await repo(),p=provider(),res=await handlePdtBoba001B01ZipUploadRecovery002(body,req(),runtime(p,r)),x=await js(res);assert.equal(res.status,200);assert.equal(x.status,"UPDATED_AND_VERIFIED");assert.equal(x.ETSY_WRITE_COUNT,1);assert.deepEqual(p.methods.filter(m=>m!=="GET"),["POST"]);assert.equal(p.files().length,5);assert.equal(p.files()[4].size_bytes,22264);});
test("ambiguous POST claims operation and a second call cannot retry",async()=>{const body=exactPdtBoba001B01ZipUploadRecovery002Body(AUTH);auth(body);const r=await repo(),p=provider({throwPost:true});let res=await handlePdtBoba001B01ZipUploadRecovery002(body,req(),runtime(p,r));assert.equal(res.status,202);assert.equal(p.writes(),1);res=await handlePdtBoba001B01ZipUploadRecovery002(body,req(),runtime(p,r));assert.equal(res.status,202);assert.equal(p.writes(),1);});
