import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";
import { beginOperation, hashOperationRequest, MemoryOperationLedgerRepository } from "../lib/operation-ledger";
import { exactPdtBoba001B01BuyerFilesBody, PDT_BOBA_001_B01_BUYER_FILES } from "../lib/pdt-boba-001-b01-buyer-files";
import { PDT_BOBA_001_B01_DESCRIPTION } from "../lib/pdt-boba-001-b01-description";
import { exactPdtBoba001B01Recovery001Body, handlePdtBoba001B01Recovery001, PDT_BOBA_001_B01_RECOVERY_001, verifyPdtBoba001B01Recovery001ProtectedState } from "../lib/pdt-boba-001-b01-buyer-files-recovery-001";

const AUTH="RECOVERY-001-AUTH";
const TAGS=["bubble tea business","boba shop toolkit","boba operations","boba shop sop","cafe opening closing","daily prep log","stock waste tracker","shift handoff log","tea cafe template","milktea inventory","cafe cleaning sheet","drink shop checklist","google sheets boba"];
const GALLERY=[[8547319609,1,2000,1600],[8547319665,2,2000,1600],[8547319731,3,1600,900],[8547319783,4,1600,900],[8547319831,5,1600,900],[8547319873,6,1600,900],[8499440812,7,1600,900],[8499440860,8,1600,900],[8499440896,9,1600,900],[8547320067,10,1600,900],[8547320117,11,1600,900],[8499441032,12,1600,900]];
const currentFiles=()=>[
 {listing_file_id:1509032655604,rank:1,filename:"PoonthaiDigital_Boba_Checklist_A4.pdf",size_bytes:17459,filetype:"application/pdf"},
 {listing_file_id:1509032655658,rank:2,filename:"PoonthaiDigital_Boba_Checklist_US_Letter.pdf",size_bytes:16632,filetype:"application/pdf"},
 {listing_file_id:1509891952828,rank:3,filename:"Boba_Read_Me_License.pdf",size_bytes:4620,filetype:"application/pdf"},
 {listing_file_id:1509980398204,rank:4,filename:"PoonthaiDigital_Boba_Shop_Operations_Tracker.zip",size_bytes:22370,filetype:"application/zip"}
];
const core=(over:Record<string,unknown>={})=>({listing_id:4560696421,shop_id:23582741,state:"active",title:"Boba Shop Operations Toolkit, Cafe Daily SOP, Checklist, Excel Google Sheets Template (Digital Download)",description:PDT_BOBA_001_B01_DESCRIPTION.description,price:{amount:1290,divisor:100,currency_code:"USD"},taxonomy_id:12476,quantity:999,who_made:"i_did",when_made:"2020_2026",listing_type:"download",tags:[...TAGS],return_policy_id:1,file_data:"3 PDF, 1 ZIP",...over});
const imgs=()=>GALLERY.map(([listing_image_id,rank,full_width,full_height])=>({listing_image_id,rank,full_width,full_height}));
const vids=()=>[{video_id:9001,height:1080,width:1080,thumbnail_url:"t",video_url:"v",video_state:"active"}];
type Opt={files?:Array<Record<string,unknown>>;listing?:Record<string,unknown>;postStatus?:number;throwPost?:boolean;failReadAfterPost?:boolean};
function provider(o:Opt={}){let files=structuredClone(o.files??currentFiles()),listing=core(o.listing),writes=0,postDone=false,readFailed=false;const methods:string[]=[];const fetchImpl=(async(input:string|URL|Request,init?:RequestInit)=>{const url=String(input),method=init?.method??"GET";methods.push(method);if(method==="POST"){writes++;postDone=true;if(o.throwPost)throw new Error("ambiguous");if(o.postStatus&&o.postStatus!==201)return Response.json({error:"rejected"},{status:o.postStatus});const form=init?.body;assert.ok(form instanceof FormData);assert.equal(String(form.get("rank")),"4");assert.equal(String(form.get("name")),"Boba_Quick_Start.pdf");const file=form.get("file");assert.ok(file instanceof File);files=files.map(f=>Number(f.rank)>=4?{...f,rank:Number(f.rank)+1}:f);files.push({listing_file_id:1600000000004,rank:4,filename:"Boba_Quick_Start.pdf",size_bytes:5305,filetype:"application/pdf"});files.sort((a,b)=>Number(a.rank)-Number(b.rank));listing=core({file_data:"4 PDF, 1 ZIP"});return Response.json({listing_file_id:1600000000004},{status:201});}if(method==="DELETE"||method==="PATCH")throw new Error(`forbidden ${method}`);if(url.endsWith("/listings/4560696421"))return Response.json(listing);if(url.endsWith("/images"))return Response.json({results:imgs()});if(url.endsWith("/properties"))return Response.json({results:[]});if(url.endsWith("/files")){if(postDone&&o.failReadAfterPost&&!readFailed){readFailed=true;return Response.json({error:"temporary"},{status:503});}return Response.json({results:structuredClone(files)});}if(url.endsWith("/videos"))return Response.json({results:vids()});return new Response("{}",{status:404});}) as typeof fetch;return{fetchImpl,writes:()=>writes,methods,files:()=>files};}
async function parentRepo(){const repo=new MemoryOperationLedgerRepository(),body=exactPdtBoba001B01BuyerFilesBody("OLD-AUTH"),begun=await beginOperation(repo,PDT_BOBA_001_B01_BUYER_FILES.operationId,body,"2026-09-12T05:00:00.000Z");assert.equal(begun.status,"STARTED");await repo.save({...begun.record,status:"RECONCILIATION_REQUIRED",recoveryPoint:"TARGET_4_DELETE_RECONCILED_READ_ONLY",receipt:{ETSY_WRITE_COUNT:1,ETSY_WRITE_ATTEMPT_COUNT:1,ETSY_WRITE_COUNT_STATUS:"CONFIRMED",reconciliationState:"SLOT_4_DELETE_CONFIRMED"},updatedAt:"2026-09-12T06:02:08.650Z"});return repo;}
function auth(body=exactPdtBoba001B01Recovery001Body(AUTH)){process.env.PUBLISH_WRITES_ENABLED="true";process.env.ETSY_B01_WRITE_TOKEN="test-write-token";process.env.ETSY_SHOP_ID="23582741";process.env.ETSY_API_KEY="k";process.env.ETSY_SHARED_SECRET="s";process.env.ETSY_BOBA_B01_RECOVERY_001_AUTHORIZATION_ID=AUTH;process.env.ETSY_BOBA_B01_RECOVERY_001_REQUEST_SHA256=hashOperationRequest(body);}
process.env.ETSY_API_KEY="k";process.env.ETSY_SHARED_SECRET="s";
const req=()=>new Request("https://example.test",{method:"POST",headers:{"x-autodigitalpublisher-write-token":"test-write-token"}});
const js=(r:Response)=>r.json() as Promise<Record<string,unknown>>;
const runtime=(p:ReturnType<typeof provider>,repo:MemoryOperationLedgerRepository)=>({repository:repo,parentRepository:repo,getAccessToken:async()=>"token",loadAsset:async()=>Buffer.alloc(5305),verifyAsset:()=>true,fetchImpl:p.fetchImpl,now:()=>"2026-09-12T06:30:00.000Z"});

 test("recovery identity reuses exact frozen B01 identity and scopes only Quick Start upload",()=>{const r=PDT_BOBA_001_B01_RECOVERY_001;assert.equal(r.operationId,"PDT-BOBA-001-B01-BUYER-FILES-RECOVERY-001");assert.equal(r.parentOperationId,PDT_BOBA_001_B01_BUYER_FILES.operationId);assert.equal(r.candidateFingerprint,PDT_BOBA_001_B01_BUYER_FILES.candidateFingerprint);assert.equal(r.buildFingerprint,PDT_BOBA_001_B01_BUYER_FILES.buildFingerprint);assert.equal(r.buildFreezeSha256,PDT_BOBA_001_B01_BUYER_FILES.buildFreezeSha256);assert.equal(r.acceptanceCriteriaSha256,PDT_BOBA_001_B01_BUYER_FILES.acceptanceCriteriaSha256);assert.equal(r.target.fileName,"Boba_Quick_Start.pdf");assert.equal(r.target.targetSizeBytes,5305);});
 test("registered in authorized operation and asset routes",()=>{const a=readFileSync(new URL("../app/api/internal/etsy/authorized-operation/route.ts",import.meta.url),"utf8"),b=readFileSync(new URL("../app/api/internal/etsy/authorized-operation/asset-chunk/route.ts",import.meta.url),"utf8");assert.match(a,/PDT_BOBA_001_B01_RECOVERY_001\.operationId/);assert.match(a,/verifyPdtBoba001B01Recovery001ProtectedState/);assert.match(b,/PDT_BOBA_001_B01_RECOVERY_001\.target\.sha256/);});
 test("fresh read-only verifier accepts exact current four-file state with zero Etsy writes",async()=>{const repo=await parentRepo(),p=provider(),r=await verifyPdtBoba001B01Recovery001ProtectedState({repository:repo,getAccessToken:async()=>"token",fetchImpl:p.fetchImpl}),x=await js(r);assert.equal(r.status,200);assert.equal(x.status,"PROTECTED_STATE_MATCH");assert.equal(x.currentBuyerFileCount,4);assert.equal(x.recoveryScope,"UPLOAD_REPLACEMENT_QUICK_START_ONLY");assert.equal(x.forbiddenMutation,"DELETE");assert.equal(x.ETSY_WRITE_COUNT,0);assert.equal(p.writes(),0);assert.equal(p.methods.some(m=>m==="DELETE"||m==="POST"||m==="PATCH"),false);});
 test("verifier fails closed if parent reconciliation evidence is missing",async()=>{const repo=new MemoryOperationLedgerRepository(),p=provider(),r=await verifyPdtBoba001B01Recovery001ProtectedState({repository:repo,getAccessToken:async()=>"token",fetchImpl:p.fetchImpl}),x=await js(r);assert.equal(r.status,409);assert.equal(x.reason,"PARENT_RECONCILIATION_MISMATCH");assert.equal(p.writes(),0);});
 test("verifier fails closed if old Quick Start unexpectedly exists",async()=>{const repo=await parentRepo(),files=currentFiles();files.splice(3,0,{listing_file_id:1509891952826,rank:4,filename:"Boba_Quick_Start.pdf",size_bytes:4564,filetype:"application/pdf"});files[4]={...files[4],rank:5};const p=provider({files,listing:{file_data:"4 PDF, 1 ZIP"}}),r=await verifyPdtBoba001B01Recovery001ProtectedState({repository:repo,getAccessToken:async()=>"token",fetchImpl:p.fetchImpl});assert.equal(r.status,409);assert.equal(p.writes(),0);});
 test("without new production authorization recovery cannot execute",async()=>{const repo=await parentRepo(),p=provider();delete process.env.ETSY_BOBA_B01_RECOVERY_001_AUTHORIZATION_ID;delete process.env.ETSY_BOBA_B01_RECOVERY_001_REQUEST_SHA256;process.env.PUBLISH_WRITES_ENABLED="true";process.env.ETSY_B01_WRITE_TOKEN="test-write-token";process.env.ETSY_SHOP_ID="23582741";const r=await handlePdtBoba001B01Recovery001(exactPdtBoba001B01Recovery001Body(AUTH),req(),runtime(p,repo));assert.equal(r.status,503);assert.equal(p.writes(),0);});
 test("successful recovery performs exactly one POST and never DELETE/PATCH",async()=>{const body=exactPdtBoba001B01Recovery001Body(AUTH);auth(body);const repo=await parentRepo(),p=provider(),r=await handlePdtBoba001B01Recovery001(body,req(),runtime(p,repo)),x=await js(r);assert.equal(r.status,200);assert.equal(x.status,"UPDATED_AND_VERIFIED");assert.equal(x.ETSY_WRITE_COUNT,1);assert.equal(p.writes(),1);assert.deepEqual(p.methods.filter(m=>m!=="GET"),["POST"]);assert.equal(p.files()[3].filename,"Boba_Quick_Start.pdf");assert.equal(p.files()[3].size_bytes,5305);assert.equal(p.files()[4].listing_file_id,1509980398204);assert.equal(p.files()[4].rank,5);});
 test("deterministic rejected upload confirms zero mutation and blocks retry",async()=>{const body=exactPdtBoba001B01Recovery001Body(AUTH);auth(body);const repo=await parentRepo(),p=provider({postStatus:400});let r=await handlePdtBoba001B01Recovery001(body,req(),runtime(p,repo)),x=await js(r);assert.equal(r.status,502);assert.equal(x.ETSY_WRITE_COUNT,0);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"CONFIRMED");assert.equal(p.writes(),1);r=await handlePdtBoba001B01Recovery001(body,req(),runtime(p,repo));assert.equal(r.status,409);assert.equal(p.writes(),1);});
 test("ambiguous upload requires reconciliation and never blind retries",async()=>{const body=exactPdtBoba001B01Recovery001Body(AUTH);auth(body);const repo=await parentRepo(),p=provider({throwPost:true});let r=await handlePdtBoba001B01Recovery001(body,req(),runtime(p,repo)),x=await js(r);assert.equal(r.status,202);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"UNRESOLVED_REQUIRES_RECONCILIATION");assert.equal(p.writes(),1);r=await handlePdtBoba001B01Recovery001(body,req(),runtime(p,repo));assert.equal(r.status,202);assert.equal(p.writes(),1);});
 test("post-upload readback failure is unresolved and does not fabricate success",async()=>{const body=exactPdtBoba001B01Recovery001Body(AUTH);auth(body);const repo=await parentRepo(),p=provider({failReadAfterPost:true});const r=await handlePdtBoba001B01Recovery001(body,req(),runtime(p,repo)),x=await js(r);assert.equal(r.status,202);assert.equal(x.ETSY_WRITE_COUNT,0);assert.equal(x.ETSY_WRITE_COUNT_STATUS,"UNRESOLVED_REQUIRES_RECONCILIATION");assert.equal(p.writes(),1);assert.deepEqual(p.methods.filter(m=>m!=="GET"),["POST"]);});
