import assert from "node:assert/strict";import test from "node:test";import {createPerformanceSnapshotRecord,MemoryPerformanceSnapshotRepository,type PerformanceObservations} from "../lib/performance-snapshots";
const obs:PerformanceObservations={views:100,visits:80,favorites:10,orders:2,revenue:20,conversionRate:2.5,etsySearchVisits:"NOT_AVAILABLE"};function make(id:string,o:PerformanceObservations=obs,start="2026-09-04T00:00:00.000Z",end="2026-09-05T00:00:00.000Z",baseline?:any){return createPerformanceSnapshotRecord({snapshotId:id,productId:"P1",listingId:"L1",windowStart:start,windowEnd:end,observations:o},baseline);}
test("persists Etsy-available values and explicit NOT_AVAILABLE fields",()=>{const r=make("S1");assert.equal(r.snapshot.metrics.views,100);assert.equal(r.snapshot.metrics.etsySearchVisits,null);assert.deepEqual(r.snapshot.unavailableFields,["etsySearchVisits"]);});
test("without baseline all deltas are unavailable",()=>{const r=make("S1");assert.equal(Object.values(r.deltas).every(v=>v===null),true);assert.equal(r.deltaUnavailableFields.length,7);});
test("baseline deltas calculate positive negative and zero changes",()=>{const b=make("B",{...obs,etsySearchVisits:40},"2026-09-03T00:00:00.000Z","2026-09-04T00:00:00.000Z");const c=make("C",{...obs,views:120,orders:1,revenue:20,etsySearchVisits:50},"2026-09-04T00:00:00.000Z","2026-09-05T00:00:00.000Z",b);assert.equal(c.deltas.views,20);assert.equal(c.deltas.orders,-1);assert.equal(c.deltas.revenue,0);assert.equal(c.deltas.etsySearchVisits,10);});
test("NOT_AVAILABLE in either side makes delta unavailable",()=>{const b=make("B");const c=make("C",{...obs,views:"NOT_AVAILABLE"},"2026-09-05T00:00:00.000Z","2026-09-06T00:00:00.000Z",b);assert.equal(c.deltas.views,null);assert.equal(c.deltas.etsySearchVisits,null);assert.ok(c.deltaUnavailableFields.includes("views"));});
test("baseline must match product/listing identity",()=>{const b=make("B");const bad=structuredClone(b);bad.snapshot.listingId="OTHER";assert.throws(()=>make("C",obs,"2026-09-05T00:00:00.000Z","2026-09-06T00:00:00.000Z",bad),/PERFORMANCE_BASELINE_IDENTITY_MISMATCH/);});
test("baseline cannot be later than current",()=>{const b=make("B",obs,"2026-09-06T00:00:00.000Z","2026-09-07T00:00:00.000Z");assert.throws(()=>make("C",obs,"2026-09-04T00:00:00.000Z","2026-09-05T00:00:00.000Z",b),/PERFORMANCE_BASELINE_AFTER_CURRENT/);});
test("invalid negative metrics fail canonical validation",()=>{assert.throws(()=>make("S",{...obs,views:-1}),/INVALID_PERFORMANCE_METRIC:views/);});
test("invalid measurement window fails canonical validation",()=>{assert.throws(()=>make("S",obs,"2026-09-05T00:00:00.000Z","2026-09-05T00:00:00.000Z"),/INVALID_PERFORMANCE_WINDOW_ORDER/);});
test("memory repository persists and loads detached snapshot",async()=>{const repo=new MemoryPerformanceSnapshotRepository(),r=make("S1");await repo.save(r);const x=await repo.load("S1");assert.deepEqual(x,r);if(!x)throw new Error();(x.snapshot as any).listingId="X";assert.equal((await repo.load("S1"))?.snapshot.listingId,"L1");});
test("same snapshot ID identical replay is idempotent; conflict fails closed",async()=>{const repo=new MemoryPerformanceSnapshotRepository();await repo.save(make("S1"));await repo.save(make("S1"));await assert.rejects(()=>repo.save(make("S1",{...obs,views:101})),/PERFORMANCE_SNAPSHOT_ID_CONFLICT/);});
test("listing history is deterministic by window end",async()=>{const repo=new MemoryPerformanceSnapshotRepository();await repo.save(make("S2",obs,"2026-09-05T00:00:00.000Z","2026-09-06T00:00:00.000Z"));await repo.save(make("S1"));assert.deepEqual((await repo.listForListing("L1")).map(x=>x.snapshot.snapshotId),["S1","S2"]);});
test("creation is read-only",()=>{const o=structuredClone(obs);createPerformanceSnapshotRecord({snapshotId:"S",productId:"P1",listingId:"L1",windowStart:"2026-09-04T00:00:00.000Z",windowEnd:"2026-09-05T00:00:00.000Z",observations:o});assert.deepEqual(o,obs);});
