import { createHash, timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";
import { PD_COFFEE_002_VISUAL_R02_RELEASE } from "../../../../../../../../lib/pd-coffee-002-visual-r02-release";
import { stageAuthorizedAssetChunk } from "../../../../../../../../lib/authorized-operation-asset-store";
export const runtime="nodejs"; export const dynamic="force-dynamic";
const TOKEN_SHA256="2d76385471783c7f56082ef55b236e8053bbeaeb60413819b045976ad311c44b";
const TOKEN_HEADER="x-pd-coffee-r02-stage-token";
function authorized(request:Request){const supplied=request.headers.get(TOKEN_HEADER)?.trim()??"";if(!supplied)return false;const actual=createHash("sha256").update(supplied,"utf8").digest("hex"),a=Buffer.from(actual),b=Buffer.from(TOKEN_SHA256);return a.length===b.length&&timingSafeEqual(a,b)}
export async function POST(request:Request){if(!authorized(request))return NextResponse.json({error:"PD_COFFEE_R02_STAGE_UNAUTHORIZED",ETSY_WRITE_COUNT:0},{status:401});let body:unknown;try{body=await request.json()}catch{return NextResponse.json({error:"PD_COFFEE_R02_STAGE_INVALID_JSON",ETSY_WRITE_COUNT:0},{status:400})}if(!body||typeof body!=="object"||Array.isArray(body))return NextResponse.json({error:"PD_COFFEE_R02_STAGE_INVALID_BODY",ETSY_WRITE_COUNT:0},{status:400});const v=body as Record<string,unknown>,operationId=typeof v.operationId==="string"?v.operationId:"",assetSha256=typeof v.assetSha256==="string"?v.assetSha256.trim().toLowerCase():"",registered=PD_COFFEE_002_VISUAL_R02_RELEASE.gallery.some(a=>a.sha256===assetSha256);if(operationId!==PD_COFFEE_002_VISUAL_R02_RELEASE.operationId||!registered)return NextResponse.json({error:"PD_COFFEE_R02_STAGE_ASSET_NOT_REGISTERED",ETSY_WRITE_COUNT:0},{status:409});const chunkIndex=Number(v.chunkIndex),chunkCount=Number(v.chunkCount),dataBase64=typeof v.dataBase64==="string"?v.dataBase64:"";try{await stageAuthorizedAssetChunk({operationId,assetSha256,chunkIndex,chunkCount,dataBase64})}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"PD_COFFEE_R02_STAGE_FAILED",ETSY_WRITE_COUNT:0},{status:409})}return NextResponse.json({status:"ASSET_CHUNK_STAGED",operationId,assetSha256,chunkIndex,chunkCount,ETSY_WRITE_COUNT:0})}
