import { resolveNextExecutableStage, type FactoryState } from "./factory-state-machine";
import type { CanonicalProductRecord } from "./product-registry";

export const INTENT_STAGE_ROUTER_VERSION = "1.0.0" as const;
export type RouterIntent = "NEW_PRODUCT"|"CONTINUE"|"STATUS"|"QC"|"PATCH"|"STOP";
export type RoutedStage = FactoryState|"PATCH_CANDIDATE"|"STOP"|"MIGRATION_REVIEW_REQUIRED"|"COMPLETE";
export type RoutedCommand = {routerVersion:typeof INTENT_STAGE_ROUTER_VERSION;intent:RouterIntent;command:"START_NEW_PRODUCT"|"CONTINUE_STAGE"|"READ_STATUS"|"RUN_INDEPENDENT_QC"|"CREATE_PATCH_CANDIDATE"|"STOP"|"REVIEW_MIGRATION"|"COMPLETE";nextExecutableStage:RoutedStage;execute:boolean;reason?:string;};
function normalize(v:string){return v.normalize("NFC").trim().toLowerCase();}
export function classifyRouterIntent(text:string):RouterIntent{const v=normalize(text);if(!v)throw new Error("EMPTY_ROUTER_INTENT");if(/^(stop|หยุด|พอ|ยกเลิก)$/.test(v))return"STOP";if(v.includes("หาสินค้าใหม่")||v.includes("new product"))return"NEW_PRODUCT";if(v.includes("patch")||v.includes("แพตช์")||v.includes("แก้ listing")||v.includes("แก้ลิสติ้ง"))return"PATCH";if(v==="qc"||v.includes("final qc")||v.includes("ตรวจ qc"))return"QC";if(v.includes("status")||v.includes("สถานะ"))return"STATUS";if(v==="ต่อ"||v.includes("ทำต่อ")||v.includes("continue"))return"CONTINUE";throw new Error("UNSUPPORTED_ROUTER_INTENT");}
function next(record:CanonicalProductRecord):{stage:RoutedStage;reason?:string}{const r=resolveNextExecutableStage(record);if(r.status==="MIGRATION_REVIEW_REQUIRED")return{stage:"MIGRATION_REVIEW_REQUIRED",reason:r.reason};return{stage:r.stage??"COMPLETE"};}
export function routeIntentToStage(input:{intentText:string;product?:CanonicalProductRecord}):RoutedCommand{const intent=classifyRouterIntent(input.intentText);const base={routerVersion:INTENT_STAGE_ROUTER_VERSION,intent};if(intent==="STOP")return{...base,command:"STOP",nextExecutableStage:"STOP",execute:false};if(intent==="NEW_PRODUCT")return{...base,command:"START_NEW_PRODUCT",nextExecutableStage:"DISCOVERED",execute:true};if(intent==="PATCH")return{...base,command:"CREATE_PATCH_CANDIDATE",nextExecutableStage:"PATCH_CANDIDATE",execute:true};if(!input.product)throw new Error("PRODUCT_CONTEXT_REQUIRED");const n=next(input.product);if(n.stage==="MIGRATION_REVIEW_REQUIRED")return{...base,command:"REVIEW_MIGRATION",nextExecutableStage:n.stage,execute:false,reason:n.reason};if(n.stage==="COMPLETE")return{...base,command:"COMPLETE",nextExecutableStage:"COMPLETE",execute:false};if(intent==="STATUS")return{...base,command:"READ_STATUS",nextExecutableStage:n.stage,execute:false};if(intent==="QC"){if(n.stage!=="FINAL_QC_PASS")return{...base,command:"CONTINUE_STAGE",nextExecutableStage:n.stage,execute:true,reason:"QC_NOT_NEXT_STAGE"};return{...base,command:"RUN_INDEPENDENT_QC",nextExecutableStage:"FINAL_QC_PASS",execute:true};}return{...base,command:"CONTINUE_STAGE",nextExecutableStage:n.stage,execute:true};}
