import { createHash, timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";
import { etsyApiHeaders } from "./etsy";
import { getValidEtsyAccessToken } from "./etsy-auth";
import { clearAuthorizedAsset, loadAuthorizedAsset } from "./authorized-operation-asset-store";
import { beginOperation, hashOperationRequest, NeonOperationLedgerRepository, recordOperationResult, type OperationLedgerRepository } from "./operation-ledger";

const WRITE_HEADER="x-autodigitalpublisher-write-token";
const SHA256=/^[a-f0-9]{64}$/;

export const PD_STOCK_005_VIDEO_R01_RELEASE=Object.freeze({
  operation:"ADD_LISTING_VIDEO_ONLY_PRESERVE_GALLERY_8_ALT_8",
  operationId:"PD-STOCK-005-VIDEO-R01-RELEASE-001",
  operationFingerprint:"e3079f5e4a245378167331dbe7c7afec5740544a33097aba2991bd629b93b173",
  authorizationId:"PD-STOCK-005-VIDEO-R01-AUTH-20260916-01",
  productId:"PD-STOCK-005",productVersion:"V1",shopId:"23582741",listingId:"4561821192",
  candidateId:"PD-STOCK-005-VIDEO-R01-CANDIDATE-20260916-01",
  candidateFingerprint:"552959afed396dbcc7a9065a02ca7121eea1724f73f4898e6ffd30f65c77cc41",
  buildId:"PD-STOCK-005-VIDEO-R01-BUILD-20260916-01",
  freezeEvidenceDriveId:"1azyEJiMSX7s9ndel_Ca7QQ8MhTWphlko",
  asset:{fileName:"PD-STOCK-005_VIDEO_inventory-waste-tracker.mp4",mimeType:"video/mp4",sizeBytes:572404,sha256:"c3e4caad850607600e839e30d7b63754d8b57c9631d4218515269b329aa3869a",driveId:"16oTMAwa4S2xHx9n--3uPEBcpZ6BjTiKB",width:1920,height:1080,durationSeconds:10.766667},
  expectedVideoCountBefore:0,expectedVideoCountAfter:1
} as const);

const TITLE="Restaurant & Cafe Inventory Tracker | Stock, Waste, Reorder and Supplier Spreadsheet";
const DESCRIPTION_SHA256="61e01e830c577c9a52dd799cab2aaee502d3b972ebf39aff4ae50c3e2c0abcd3";
const TAGS=["restaurant inventory","cafe stock tracker","kitchen inventory","food waste tracker","reorder spreadsheet","supplier tracker","par level sheet","stock count sheet","stock control","inventory excel","google sheets stock","waste cost log","food stocktake"];
const GALLERY=[
  [8580511217,1,2500,2000,"Restaurant and cafe inventory and waste tracker hero showing a real Excel workbook Start Here preview with count, waste and reorder workflow and eight workbook tabs."],
  [8532646756,2,2500,2000,"Inventory tracker gallery image listing the eight workbook tabs—Start Here, Item Master, Daily Count, Waste Log, Reorder Plan, Suppliers, Weekly Summary and Blank Tracker—beside a real workbook preview."],
  [8580511355,3,2500,2000,"Real Daily Count worksheet preview showing opening, received, used, waste, calculated closing, physical closing and variance fields for inventory review."],
  [8580511435,4,2500,2000,"Real Waste Log worksheet preview showing quantity wasted, reason, unit cost, waste cost and recorded-by fields for restaurant and cafe inventory tracking."],
  [8532646976,5,2500,2000,"Real Reorder Plan worksheet preview showing current stock, reorder level, suggested order quantity, unit cost, estimated cost and order status fields."],
  [8532647054,6,2500,2000,"Real Item Master and Suppliers worksheet previews showing par and reorder settings, primary supplier details, lead time and supplier status fields."],
  [8580511641,7,2500,2000,"Real Weekly Summary worksheet preview showing stock value, purchases, usage value, waste cost, waste percentage and items reordered for manager review."],
  [8532647190,8,2500,2000,"Digital download overview showing a real Excel workbook preview and A4 printable PDF cover, with A4 and US Letter PDFs, Quick Start, and Read Me plus License files included."]
] as const;
const FILES=[[1509497762118,1,"Inventory_Waste_A4.pdf",24247,"application/pdf"],[1509497762234,2,"Inventory_Waste_US_Letter.pdf",23237,"application/pdf"],[1509497762284,3,"Inventory_Waste_Quick_Start.pdf",4630,"application/pdf"],[1510700238185,4,"Inventory_Waste_Read_Me_License.pdf",4242,"application/pdf"],[1509980203922,5,"Inventory_Waste_Tracker.zip",16285,"application/zip"]] as const;

type Rec=Record<string,unknown>;
type State={listing:Rec;images:Rec[];attributes:Rec[];files:Rec[];videos:Rec[];statuses:Record<string,number>};
export type PdStock005VideoR01Runtime={fetchImpl?:typeof fetch;getAccessToken?:()=>Promise<string>;repository?:OperationLedgerRepository;loadAsset?:()=>Promise<Buffer>;clearAsset?:()=>Promise<void>;verifyAsset?:(bytes:Buffer)=>boolean;sleep?:(ms:number)=>Promise<void>;now?:()=>string};
const isRec=(v:unknown):v is Rec=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const results=(v:unknown)=>isRec(v)&&Array.isArray(v.results)?v.results.filter(isRec):null;
const hashText=(v:unknown)=>createHash("sha256").update(typeof v==="string"?v.normalize("NFC"):"","utf8").digest("hex");
const secureEqual=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
async function json(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return {}}}
function multipartHeaders(token:string){const h=etsyApiHeaders(token);delete h["content-type"];return h}
function imageRows(s:State){return [...s.images].sort((a,b)=>Number(a.rank)-Number(b.rank)).map(i=>[Number(i.listing_image_id),Number(i.rank),Number(i.full_width),Number(i.full_height),String(i.alt_text??"")]);}
function fileRows(s:State){return [...s.files].sort((a,b)=>Number(a.rank)-Number(b.rank)).map(f=>[Number(f.listing_file_id),Number(f.rank),String(f.filename??""),Number(f.size_bytes),String(f.filetype??"")]);}
function videoRows(v:Rec[]){return [...v].map(x=>({videoId:Number(x.video_id),width:Number(x.width),height:Number(x.height),videoState:String(x.video_state??""),videoUrl:String(x.video_url??"")})).sort((a,b)=>a.videoId-b.videoId)}
async function readState(token:string,fetchImpl:typeof fetch):Promise<State>{const base="https://api.etsy.com/v3/application",shop=PD_STOCK_005_VIDEO_R01_RELEASE.shopId,listing=PD_STOCK_005_VIDEO_R01_RELEASE.listingId;const urls={listing:`${base}/listings/${listing}`,images:`${base}/listings/${listing}/images`,attributes:`${base}/shops/${shop}/listings/${listing}/properties`,files:`${base}/shops/${shop}/listings/${listing}/files`,videos:`${base}/listings/${listing}/videos`};const entries=await Promise.all(Object.entries(urls).map(async([name,url])=>{const response=await fetchImpl(url,{method:"GET",headers:etsyApiHeaders(token),cache:"no-store"});return{name,response,value:await json(response)}}));const by=Object.fromEntries(entries.map(e=>[e.name,e])) as Record<string,{response:Response;value:unknown}>;const images=results(by.images.value),attributes=results(by.attributes.value),files=results(by.files.value),videos=results(by.videos.value);if(!by.listing.response.ok||!isRec(by.listing.value)||!by.images.response.ok||!by.attributes.response.ok||!by.files.response.ok||!by.videos.response.ok||!images||!attributes||!files||!videos)throw new Error("PD_STOCK_005_VIDEO_R01_READBACK_FAILED");return{listing:by.listing.value,images,attributes,files,videos,statuses:Object.fromEntries(entries.map(e=>[e.name,e.response.status]))}}
function coreMatches(s:State){const l=s.listing,p=isRec(l.price)?l.price:{};if(String(l.listing_id)!==PD_STOCK_005_VIDEO_R01_RELEASE.listingId||String(l.shop_id)!==PD_STOCK_005_VIDEO_R01_RELEASE.shopId||l.state!=="active"||l.title!==TITLE||hashText(l.description)!==DESCRIPTION_SHA256)return false;if(JSON.stringify(l.tags)!==JSON.stringify(TAGS)||Number(p.amount)!==890||Number(p.divisor)!==100||p.currency_code!=="USD"||Number(l.taxonomy_id)!==12476||Number(l.quantity)!==999||l.who_made!=="i_did"||l.when_made!=="2020_2026"||(l.listing_type??l.type)!=="download"||Number(l.return_policy_id)!==1||l.file_data!=="4 PDF, 1 ZIP"||s.attributes.length!==0)return false;return JSON.stringify(imageRows(s))===JSON.stringify(GALLERY)&&JSON.stringify(fileRows(s))===JSON.stringify(FILES)}
function preWriteMatches(s:State){return coreMatches(s)&&s.videos.length===0}
function protectedSnapshot(s:State){const l=s.listing,p=isRec(l.price)?l.price:{};return{listingId:Number(l.listing_id),shopId:Number(l.shop_id),state:l.state,title:l.title,descriptionSha256:hashText(l.description),tags:l.tags,price:{amount:Number(p.amount),divisor:Number(p.divisor),currencyCode:p.currency_code},taxonomyId:Number(l.taxonomy_id),quantity:Number(l.quantity),whoMade:l.who_made,whenMade:l.when_made,listingType:l.listing_type??l.type,returnPolicyId:Number(l.return_policy_id),fileData:l.file_data,images:imageRows(s),attributes:s.attributes,files:fileRows(s),videoCount:s.videos.length} as Record<string,unknown>}
function assetMatches(bytes:Buffer){const a=PD_STOCK_005_VIDEO_R01_RELEASE.asset;return bytes.length===a.sizeBytes&&createHash("sha256").update(bytes).digest("hex")===a.sha256}
function authError(request:Request){const expected=process.env.ETSY_B01_WRITE_TOKEN?.trim()??"",supplied=request.headers.get(WRITE_HEADER)?.trim()??"";if(!expected)return NextResponse.json({error:"PD_STOCK_VIDEO_R01_WRITE_AUTH_NOT_CONFIGURED",ETSY_WRITE_COUNT:0},{status:503});if(!supplied||!secureEqual(supplied,expected))return NextResponse.json({error:"PD_STOCK_VIDEO_R01_UNAUTHORIZED",ETSY_WRITE_COUNT:0},{status:401});return null}
export function exactPdStock005VideoR01AuthorizationHash(psv:string){return hashOperationRequest({authorizationId:PD_STOCK_005_VIDEO_R01_RELEASE.authorizationId,operationId:PD_STOCK_005_VIDEO_R01_RELEASE.operationId,operationFingerprint:PD_STOCK_005_VIDEO_R01_RELEASE.operationFingerprint,candidateFingerprint:PD_STOCK_005_VIDEO_R01_RELEASE.candidateFingerprint,scope:PD_STOCK_005_VIDEO_R01_RELEASE.operation,protectedStateFingerprint:psv.trim().toLowerCase()})}
function exactBody(psv:string){return{operation:PD_STOCK_005_VIDEO_R01_RELEASE.operation,operationId:PD_STOCK_005_VIDEO_R01_RELEASE.operationId,operationFingerprint:PD_STOCK_005_VIDEO_R01_RELEASE.operationFingerprint,authorizationId:PD_STOCK_005_VIDEO_R01_RELEASE.authorizationId,productId:PD_STOCK_005_VIDEO_R01_RELEASE.productId,listingId:PD_STOCK_005_VIDEO_R01_RELEASE.listingId,candidateId:PD_STOCK_005_VIDEO_R01_RELEASE.candidateId,candidateFingerprint:PD_STOCK_005_VIDEO_R01_RELEASE.candidateFingerprint,buildId:PD_STOCK_005_VIDEO_R01_RELEASE.buildId,protectedStateFingerprint:psv.trim().toLowerCase(),asset:{...PD_STOCK_005_VIDEO_R01_RELEASE.asset}}}
export async function verifyPdStock005VideoR01ProtectedState(runtime:PdStock005VideoR01Runtime={}){try{const token=await(runtime.getAccessToken??getValidEtsyAccessToken)(),state=await readState(token,runtime.fetchImpl??fetch),match=preWriteMatches(state),psv=hashOperationRequest(protectedSnapshot(state));return NextResponse.json({status:match?"PROTECTED_STATE_MATCH":"PROTECTED_STATE_MISMATCH",operationId:PD_STOCK_005_VIDEO_R01_RELEASE.operationId,operationFingerprint:PD_STOCK_005_VIDEO_R01_RELEASE.operationFingerprint,candidateFingerprint:PD_STOCK_005_VIDEO_R01_RELEASE.candidateFingerprint,protectedStateFingerprint:psv,expectedAuthorizationRequestHash:exactPdStock005VideoR01AuthorizationHash(psv),galleryCount:state.images.length,videoCount:state.videos.length,providerReadStatus:state.statuses,scope:PD_STOCK_005_VIDEO_R01_RELEASE.operation,ETSY_WRITE_COUNT:0},{status:match?200:409})}catch{return NextResponse.json({error:"PD_STOCK_VIDEO_R01_PROTECTED_STATE_READ_FAILED",ETSY_WRITE_COUNT:0},{status:502})}}
async function poll(token:string,fetchImpl:typeof fetch,predicate:(s:State)=>boolean,sleep:(ms:number)=>Promise<void>){let last:State|null=null;for(let i=0;i<8;i++){try{last=await readState(token,fetchImpl);if(predicate(last))return last}catch{}if(i<7)await sleep(1000)}return last}
export async function handlePdStock005VideoR01Release(psv:string,authorizationRequestHash:string,request:Request,runtime:PdStock005VideoR01Runtime={}){if(process.env.PUBLISH_WRITES_ENABLED!=="true")return NextResponse.json({error:"PD_STOCK_VIDEO_R01_WRITES_DISABLED",ETSY_WRITE_COUNT:0},{status:403});const ae=authError(request);if(ae)return ae;const protectedSha=psv.trim().toLowerCase(),authHash=authorizationRequestHash.trim().toLowerCase();if(!SHA256.test(protectedSha)||!SHA256.test(authHash)||!secureEqual(exactPdStock005VideoR01AuthorizationHash(protectedSha),authHash))return NextResponse.json({error:"PD_STOCK_VIDEO_R01_EXACT_AUTHORIZATION_BINDING_REQUIRED",ETSY_WRITE_COUNT:0},{status:409});const repo=runtime.repository??new NeonOperationLedgerRepository(),body=exactBody(protectedSha),requestHash=hashOperationRequest(body),existing=await repo.load(PD_STOCK_005_VIDEO_R01_RELEASE.operationId);if(existing){if(existing.requestHash!==requestHash)return NextResponse.json({error:"OPERATION_ID_PAYLOAD_MISMATCH",ETSY_WRITE_COUNT:0},{status:409});if(existing.status==="SUCCEEDED")return NextResponse.json({status:"REPLAY",operationId:existing.operationId,receipt:existing.receipt,ETSY_WRITE_COUNT:0});return NextResponse.json({error:"PD_STOCK_VIDEO_R01_ALREADY_CLAIMED_DO_NOT_RETRY",ledgerStatus:existing.status,receipt:existing.receipt,ETSY_WRITE_COUNT:Number(existing.receipt?.ETSY_WRITE_COUNT)||0},{status:existing.status==="RECONCILIATION_REQUIRED"?202:409})}
  let bytes:Buffer;try{bytes=runtime.loadAsset?await runtime.loadAsset():await loadAuthorizedAsset(PD_STOCK_005_VIDEO_R01_RELEASE.operationId,PD_STOCK_005_VIDEO_R01_RELEASE.asset.sha256)}catch{return NextResponse.json({error:"PD_STOCK_VIDEO_R01_ASSET_NOT_STAGED",ETSY_WRITE_COUNT:0},{status:409})}if(!(runtime.verifyAsset??assetMatches)(bytes))return NextResponse.json({error:"PD_STOCK_VIDEO_R01_ASSET_IDENTITY_MISMATCH",ETSY_WRITE_COUNT:0},{status:409});
  const fetchImpl=runtime.fetchImpl??fetch,token=await(runtime.getAccessToken??getValidEtsyAccessToken)(),sleep=runtime.sleep??((ms:number)=>new Promise(r=>setTimeout(r,ms)));let before:State;try{before=await readState(token,fetchImpl)}catch{return NextResponse.json({error:"PD_STOCK_VIDEO_R01_PREREAD_FAILED",ETSY_WRITE_COUNT:0},{status:502})}if(!preWriteMatches(before))return NextResponse.json({error:"PD_STOCK_VIDEO_R01_PROTECTED_STATE_MISMATCH",ETSY_WRITE_COUNT:0},{status:409});const actualPsv=hashOperationRequest(protectedSnapshot(before));if(!secureEqual(actualPsv,protectedSha))return NextResponse.json({error:"PD_STOCK_VIDEO_R01_FRESH_PSV_FINGERPRINT_MISMATCH",actualProtectedStateFingerprint:actualPsv,ETSY_WRITE_COUNT:0},{status:409});const begun=await beginOperation(repo,PD_STOCK_005_VIDEO_R01_RELEASE.operationId,body,runtime.now?.()??new Date().toISOString());if(begun.status==="REPLAY")return NextResponse.json({error:"PD_STOCK_VIDEO_R01_ALREADY_CLAIMED_DO_NOT_RETRY",ETSY_WRITE_COUNT:0},{status:409});
  const form=new FormData();form.set("name",PD_STOCK_005_VIDEO_R01_RELEASE.asset.fileName);form.set("video",new File([new Uint8Array(bytes)],PD_STOCK_005_VIDEO_R01_RELEASE.asset.fileName,{type:"video/mp4"}));const videosUrl=`https://api.etsy.com/v3/application/shops/${PD_STOCK_005_VIDEO_R01_RELEASE.shopId}/listings/${PD_STOCK_005_VIDEO_R01_RELEASE.listingId}/videos`;let upload:Response;try{upload=await fetchImpl(videosUrl,{method:"POST",headers:multipartHeaders(token),body:form,cache:"no-store"})}catch{await recordOperationResult(repo,begun.record.operationId,begun.record.requestHash,"RECONCILIATION_REQUIRED",runtime.now?.()??new Date().toISOString(),{recoveryPoint:"VIDEO_UPLOAD_RESPONSE_AMBIGUOUS",receipt:{ETSY_WRITE_COUNT:0,ETSY_WRITE_ATTEMPT_COUNT:1}});return NextResponse.json({error:"PD_STOCK_VIDEO_R01_UPLOAD_AMBIGUOUS_DO_NOT_RETRY",ETSY_WRITE_COUNT:0,ETSY_WRITE_ATTEMPT_COUNT:1},{status:202})}const uploadBody=await json(upload),newVideoId=isRec(uploadBody)?Number(uploadBody.video_id):NaN;if(upload.status!==201||!Number.isSafeInteger(newVideoId)||newVideoId<1){await recordOperationResult(repo,begun.record.operationId,begun.record.requestHash,upload.status>=500?"RECONCILIATION_REQUIRED":"FAILED",runtime.now?.()??new Date().toISOString(),{recoveryPoint:"VIDEO_UPLOAD_REJECTED",receipt:{providerUploadStatus:upload.status,ETSY_WRITE_COUNT:0,ETSY_WRITE_ATTEMPT_COUNT:1}});return NextResponse.json({error:"PD_STOCK_VIDEO_R01_UPLOAD_NOT_VERIFIED_DO_NOT_RETRY",providerStatus:upload.status,ETSY_WRITE_COUNT:0,ETSY_WRITE_ATTEMPT_COUNT:1},{status:upload.status>=500?202:502})}
  const final=await poll(token,fetchImpl,s=>coreMatches(s)&&videoRows(s.videos).length===1&&videoRows(s.videos)[0]?.videoId===newVideoId&&videoRows(s.videos)[0]?.videoState==="active",sleep),meta=final?videoRows(final.videos)[0]:undefined;if(!final||!meta||meta.width!==1920||meta.height!==1080||!meta.videoUrl){await recordOperationResult(repo,begun.record.operationId,begun.record.requestHash,"RECONCILIATION_REQUIRED",runtime.now?.()??new Date().toISOString(),{recoveryPoint:"FINAL_VIDEO_READBACK_UNVERIFIED",receipt:{providerUploadStatus:upload.status,newVideoId,ETSY_WRITE_COUNT:1,ETSY_WRITE_ATTEMPT_COUNT:1}});return NextResponse.json({error:"PD_STOCK_VIDEO_R01_FINAL_READBACK_FAILED_DO_NOT_RETRY",newVideoId,providerVideo:meta??null,ETSY_WRITE_COUNT:1,ETSY_WRITE_ATTEMPT_COUNT:1},{status:202})}
  const receipt={scope:PD_STOCK_005_VIDEO_R01_RELEASE.operation,providerUploadStatus:upload.status,newVideoId,videoState:meta.videoState,width:meta.width,height:meta.height,sourceAssetSha256:PD_STOCK_005_VIDEO_R01_RELEASE.asset.sha256,protectedStateFingerprint:protectedSha,verified:{galleryExact8Alt8:"PASS",videoCountOne:"PASS",videoActive:"PASS",title:"PRESERVED",description:"PRESERVED",tags:"PRESERVED",price:"PRESERVED",taxonomy:"PRESERVED",quantity:"PRESERVED",buyerFiles:"PRESERVED",attributes:"PRESERVED"},ETSY_WRITE_COUNT:1,ETSY_WRITE_ATTEMPT_COUNT:1};await recordOperationResult(repo,begun.record.operationId,begun.record.requestHash,"SUCCEEDED",runtime.now?.()??new Date().toISOString(),{recoveryPoint:"VIDEO_UPLOAD_VERIFIED",receipt});try{if(runtime.clearAsset)await runtime.clearAsset();else await clearAuthorizedAsset(PD_STOCK_005_VIDEO_R01_RELEASE.operationId,PD_STOCK_005_VIDEO_R01_RELEASE.asset.sha256)}catch{}return NextResponse.json({status:"UPDATED_AND_VERIFIED",mode:"WRITE_ONCE",operationId:PD_STOCK_005_VIDEO_R01_RELEASE.operationId,requestHash:begun.record.requestHash,ledgerStatus:"SUCCEEDED",newVideoId,videoState:meta.videoState,width:meta.width,height:meta.height,ETSY_WRITE_COUNT:1,ETSY_WRITE_ATTEMPT_COUNT:1,receipt});}
