import { createHash, timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";
import { etsyApiHeaders } from "./etsy";
import { getValidEtsyAccessToken } from "./etsy-auth";
import { beginOperation, hashOperationRequest, NeonOperationLedgerRepository, recordOperationResult, type OperationLedgerRepository } from "./operation-ledger";

const WRITE_HEADER = "x-autodigitalpublisher-write-token";
const SHA256 = /^[a-f0-9]{64}$/;
const AUTHORIZATION_ID_ENV = "ETSY_BOBA_B01_DESCRIPTION_AUTHORIZATION_ID";
const REQUEST_SHA_ENV = "ETSY_BOBA_B01_DESCRIPTION_REQUEST_SHA256";

const TARGET_DESCRIPTION = "Run your boba or bubble tea shop with one practical daily operations toolkit instead of scattered checklists.\n\nThis digital download includes a 9-tab editable workbook plus print-ready PDFs for the core routines your team repeats every day: opening, closing, prep, cleaning, stock & waste, cash and shift handoff.\n\nWHAT YOU GET\n• 9-tab Excel workbook: Start Here, Opening, Closing, Prep Log, Cleaning, Stock & Waste, Cash & Handoff, Blank Checklist, Setup Assistant\n• A4 printable checklist PDF — 8 pages\n• US Letter printable checklist PDF — 8 pages\n• Quick Start PDF — 2 pages\n• Read Me / License PDF — 2 pages\n• Google Sheets compatible workflow\n\nBEST FOR\nBoba shops, bubble tea shops, drink shops, owners, managers and teams that want a repeatable daily shop routine.\n\nUSE IT FOR\n• Opening and closing routines\n• Prep tracking\n• Cleaning routines\n• Stock and waste logging\n• Cash and shift handoff\n• Creating your own reusable checklist with the blank tab\n\nHOW IT WORKS\n1. Purchase and download the digital files.\n2. Open the Quick Start guide.\n3. Open the workbook in Excel or use the compatible Google Sheets workflow.\n4. Customize the editable fields for your shop.\n5. Use the workbook digitally or print the included A4 / US Letter PDFs.\n\nIMPORTANT\nThis is a digital download. No physical item will be shipped.\nThe toolkit is for internal shop organization and workflow support. It does not provide legal, food-safety, accounting, tax, payroll, POS, or compliance certification advice.\nLicense and usage instructions are included.\n\nProduct: PDT-BOBA-001 V1.";

export const PDT_BOBA_001_B01_DESCRIPTION = Object.freeze({
  operation: "UPDATE_ACTIVE_LISTING_DESCRIPTION_ONLY",
  operationId: "PDT-BOBA-001-B01-DESCRIPTION-ONLY-001",
  productId: "PDT-BOBA-001", productVersion: "V1", shopId: "23582741", listingId: "4560696421",
  candidateId: "ETSY-RESET-V1-PDT-BOBA-001-V1-2026-09-06-B01",
  candidateFingerprint: "e478bf31dc1a4c92ed0be9318d076db047c17afbd38b58cad0e7f2557eb40041",
  buildId: "ETSY-RESET-V1-PDT-BOBA-001-BUILD-20260906-B01",
  buildFingerprint: "e478bf31dc1a4c92ed0be9318d076db047c17afbd38b58cad0e7f2557eb40041",
  acceptanceCriteriaSha256: "2933a096363420086b941cd24dcf3d04285deaa0ffd40beffabcf4598233b66e",
  protectedStateBaselineSha256: "98dbbbefb7c5b59a921815edb9d23c39149033d7ba2f56794e3c9339a978f185",
  targetDescriptionSha256: "e65559f7dbe075f7105503430ef539fc4d4ae8abd7ba40478d12b71f863f86c2",
  description: TARGET_DESCRIPTION
} as const);

const EXPECTED = Object.freeze({
  title: "Boba Shop Operations Toolkit, Cafe Daily SOP, Checklist, Excel Google Sheets Template (Digital Download)",
  tags: ["bubble tea business", "boba shop toolkit", "boba operations", "boba shop sop", "cafe opening closing", "daily prep log", "stock waste tracker", "shift handoff log", "tea cafe template", "milktea inventory", "cafe cleaning sheet", "drink shop checklist", "google sheets boba"] as readonly string[],
  beforeDescriptionSha256: "d0dc4d675c55ce4ff8542b2422021a4028e2abc7479f36b27b33d9f3c58b41e4",
  price: [1290, 100, "USD"] as const, taxonomyId: 12476, quantity: 999, whoMade: "i_did", whenMade: "2020_2026", listingType: "download",
  gallery: [[8485017526,1],[8485017504,2],[8532915667,3],[8532915695,4],[8485017508,5],[8532915683,6],[8485017512,7],[8485017510,8],[8532915679,9],[8485017528,10]] as readonly (readonly number[])[],
  buyerFiles: [[1509032655604,1,"PoonthaiDigital_Boba_Checklist_A4.pdf",17459,"application/pdf"],[1509032655658,2,"PoonthaiDigital_Boba_Checklist_US_Letter.pdf",16632,"application/pdf"],[1509891952828,3,"Boba_Read_Me_License.pdf",4620,"application/pdf"],[1509891952826,4,"Boba_Quick_Start.pdf",4564,"application/pdf"],[1509980398204,5,"PoonthaiDigital_Boba_Shop_Operations_Tracker.zip",22370,"application/zip"]] as readonly (readonly (number|string)[])[]
});

type Rec=Record<string,unknown>; type State={listing:Rec;images:Rec[];attributes:Rec[];files:Rec[];statuses:Record<string,number>};
export type PdtBoba001B01Runtime={fetchImpl?:typeof fetch;getAccessToken?:()=>Promise<string>;repository?:OperationLedgerRepository;now?:()=>string};
const isRec=(v:unknown):v is Rec=>typeof v==="object"&&v!==null&&!Array.isArray(v);
const hashText=(v:string)=>createHash("sha256").update(v.normalize("NFC"),"utf8").digest("hex");
const secureEqual=(a:string,b:string)=>{const x=Buffer.from(a),y=Buffer.from(b);return x.length===y.length&&timingSafeEqual(x,y)};
async function json(r:Response){const t=await r.text();try{return t?JSON.parse(t):{}}catch{return{}}}
function results(v:unknown){return isRec(v)&&Array.isArray(v.results)?v.results.filter(isRec):null}

export function exactPdtBoba001B01DescriptionBody(authorizationId:string){return {operation:PDT_BOBA_001_B01_DESCRIPTION.operation,operationId:PDT_BOBA_001_B01_DESCRIPTION.operationId,authorizationId,productId:PDT_BOBA_001_B01_DESCRIPTION.productId,productVersion:PDT_BOBA_001_B01_DESCRIPTION.productVersion,shopId:PDT_BOBA_001_B01_DESCRIPTION.shopId,listingId:PDT_BOBA_001_B01_DESCRIPTION.listingId,candidateId:PDT_BOBA_001_B01_DESCRIPTION.candidateId,candidateFingerprint:PDT_BOBA_001_B01_DESCRIPTION.candidateFingerprint,buildId:PDT_BOBA_001_B01_DESCRIPTION.buildId,buildFingerprint:PDT_BOBA_001_B01_DESCRIPTION.buildFingerprint,acceptanceCriteriaSha256:PDT_BOBA_001_B01_DESCRIPTION.acceptanceCriteriaSha256,protectedStateBaselineSha256:PDT_BOBA_001_B01_DESCRIPTION.protectedStateBaselineSha256,targetDescriptionSha256:PDT_BOBA_001_B01_DESCRIPTION.targetDescriptionSha256,patch:{description:PDT_BOBA_001_B01_DESCRIPTION.description}}}
function exact(body:Rec,auth:string){return JSON.stringify(body)===JSON.stringify(exactPdtBoba001B01DescriptionBody(auth))}
async function readState(token:string,f:typeof fetch):Promise<State>{const b="https://api.etsy.com/v3/application",l=PDT_BOBA_001_B01_DESCRIPTION.listingId,s=PDT_BOBA_001_B01_DESCRIPTION.shopId;const urls={listing:`${b}/listings/${l}`,images:`${b}/listings/${l}/images`,attributes:`${b}/shops/${s}/listings/${l}/properties`,files:`${b}/shops/${s}/listings/${l}/files`};const es=await Promise.all(Object.entries(urls).map(async([name,url])=>{const response=await f(url,{method:"GET",headers:etsyApiHeaders(token),cache:"no-store"});return{name,response,value:await json(response)}}));const by=Object.fromEntries(es.map(e=>[e.name,e])) as Record<string,{response:Response;value:unknown}>;const images=results(by.images.value),attributes=results(by.attributes.value),files=results(by.files.value);if(!by.listing.response.ok||!isRec(by.listing.value)||!by.images.response.ok||!by.attributes.response.ok||!by.files.response.ok||!images||!attributes||!files)throw new Error("PDT_BOBA_001_B01_READ_FAILED");return{listing:by.listing.value,images,attributes,files,statuses:Object.fromEntries(es.map(e=>[e.name,e.response.status]))}}
function protectedMatches(s:State){const l=s.listing,p=isRec(l.price)?l.price:{};if(String(l.shop_id)!==PDT_BOBA_001_B01_DESCRIPTION.shopId||String(l.state).toLowerCase()!=="active"||l.title!==EXPECTED.title||JSON.stringify(l.tags)!==JSON.stringify(EXPECTED.tags))return false;if(Number(p.amount)!==EXPECTED.price[0]||Number(p.divisor)!==EXPECTED.price[1]||p.currency_code!==EXPECTED.price[2]||Number(l.taxonomy_id)!==EXPECTED.taxonomyId||Number(l.quantity)!==EXPECTED.quantity||l.who_made!==EXPECTED.whoMade||l.when_made!==EXPECTED.whenMade||(l.listing_type??l.type)!==EXPECTED.listingType||s.attributes.length!==0)return false;const g=[...s.images].sort((a,b)=>Number(a.rank)-Number(b.rank)).map(x=>[Number(x.listing_image_id),Number(x.rank)]);const files=[...s.files].sort((a,b)=>Number(a.rank)-Number(b.rank)).map(x=>[Number(x.listing_file_id),Number(x.rank),x.filename,Number(x.size_bytes),x.filetype]);return JSON.stringify(g)===JSON.stringify(EXPECTED.gallery)&&JSON.stringify(files)===JSON.stringify(EXPECTED.buyerFiles)}
const beforeMatches=(s:State)=>protectedMatches(s)&&typeof s.listing.description==="string"&&hashText(s.listing.description)===EXPECTED.beforeDescriptionSha256;
const finalMatches=(s:State)=>protectedMatches(s)&&s.listing.description===PDT_BOBA_001_B01_DESCRIPTION.description;
function authError(req:Request){const e=process.env.ETSY_B01_WRITE_TOKEN?.trim()??"",v=req.headers.get(WRITE_HEADER)?.trim()??"";if(!e)return NextResponse.json({error:"PDT_BOBA_001_B01_WRITE_AUTH_NOT_CONFIGURED",providerPatchCount:0},{status:503});if(!v||!secureEqual(v,e))return NextResponse.json({error:"PDT_BOBA_001_B01_UNAUTHORIZED",providerPatchCount:0},{status:401});return null}

export async function verifyPdtBoba001B01ProtectedState(runtime:PdtBoba001B01Runtime={}){try{const token=await(runtime.getAccessToken??getValidEtsyAccessToken)();const state=await readState(token,runtime.fetchImpl??fetch);const match=beforeMatches(state);return NextResponse.json({status:match?"PROTECTED_STATE_MATCH":"PROTECTED_STATE_MISMATCH",operationId:PDT_BOBA_001_B01_DESCRIPTION.operationId,providerPatchCount:0,ETSY_WRITE_COUNT:0,readStatus:state.statuses},{status:match?200:409})}catch{return NextResponse.json({error:"PDT_BOBA_001_B01_VERIFICATION_FAILED",providerPatchCount:0,ETSY_WRITE_COUNT:0},{status:502})}}

export async function handlePdtBoba001B01Description(body:Rec,req:Request,runtime:PdtBoba001B01Runtime={}){
 if(process.env.PUBLISH_WRITES_ENABLED!=="true")return NextResponse.json({error:"PDT_BOBA_001_B01_WRITES_DISABLED",providerPatchCount:0},{status:403});const ae=authError(req);if(ae)return ae;
 if(hashText(PDT_BOBA_001_B01_DESCRIPTION.description)!==PDT_BOBA_001_B01_DESCRIPTION.targetDescriptionSha256)return NextResponse.json({error:"PDT_BOBA_001_B01_TARGET_FINGERPRINT_MISMATCH",providerPatchCount:0},{status:409});
 if(process.env.ETSY_SHOP_ID?.trim()!==PDT_BOBA_001_B01_DESCRIPTION.shopId)return NextResponse.json({error:"PDT_BOBA_001_B01_SHOP_MISMATCH",providerPatchCount:0},{status:409});const auth=process.env[AUTHORIZATION_ID_ENV]?.trim()??"",allowed=process.env[REQUEST_SHA_ENV]?.trim().toLowerCase()??"";if(!auth||!SHA256.test(allowed))return NextResponse.json({error:"PDT_BOBA_001_B01_PRODUCTION_AUTH_NOT_CONFIGURED",providerPatchCount:0},{status:503});if(!exact(body,auth)||!secureEqual(hashOperationRequest(body),allowed))return NextResponse.json({error:"PDT_BOBA_001_B01_AUTHORIZATION_CONTRACT_MISMATCH",providerPatchCount:0},{status:409});
 const repo=runtime.repository??new NeonOperationLedgerRepository(),existing=await repo.load(PDT_BOBA_001_B01_DESCRIPTION.operationId);if(existing?.requestHash!==undefined&&existing.requestHash!==allowed)return NextResponse.json({error:"OPERATION_ID_PAYLOAD_MISMATCH",providerPatchCount:0},{status:409});if(existing?.status==="SUCCEEDED")return NextResponse.json({status:"REPLAY",mode:"WRITE_ONCE",operationId:existing.operationId,requestHash:existing.requestHash,ledgerStatus:existing.status,providerPatchCount:0,receipt:existing.receipt});
 const f=runtime.fetchImpl??fetch,token=await(runtime.getAccessToken??getValidEtsyAccessToken)();let before:State;try{before=await readState(token,f)}catch{return NextResponse.json({error:"PDT_BOBA_001_B01_PREREAD_FAILED",providerPatchCount:0},{status:502})}if(existing){if(finalMatches(before)){const done=await recordOperationResult(repo,existing.operationId,existing.requestHash,"SUCCEEDED",runtime.now?.()??new Date().toISOString(),{receipt:{...(existing.receipt??{}),reconciled:true,providerPatchCount:0}});return NextResponse.json({status:"RECONCILED",mode:"WRITE_ONCE",operationId:done.operationId,requestHash:done.requestHash,ledgerStatus:done.status,providerPatchCount:0,receipt:done.receipt})}return NextResponse.json({error:"PDT_BOBA_001_B01_ALREADY_CLAIMED",providerPatchCount:0},{status:409})}if(!beforeMatches(before))return NextResponse.json({error:"PDT_BOBA_001_B01_PROTECTED_STATE_MISMATCH",providerPatchCount:0},{status:409});
 const now=runtime.now?.()??new Date().toISOString(),begun=await beginOperation(repo,PDT_BOBA_001_B01_DESCRIPTION.operationId,body,now);if(begun.status==="REPLAY")return NextResponse.json({error:"PDT_BOBA_001_B01_ALREADY_CLAIMED",providerPatchCount:0},{status:409});const form=new URLSearchParams();form.set("description",PDT_BOBA_001_B01_DESCRIPTION.description);let patch:Response|null=null;try{patch=await f(`https://api.etsy.com/v3/application/shops/${PDT_BOBA_001_B01_DESCRIPTION.shopId}/listings/${PDT_BOBA_001_B01_DESCRIPTION.listingId}`,{method:"PATCH",headers:{...etsyApiHeaders(token),"content-type":"application/x-www-form-urlencoded"},body:form,cache:"no-store"});await json(patch)}catch{}
 if(patch&&!patch.ok&&patch.status<500){await recordOperationResult(repo,begun.record.operationId,begun.record.requestHash,"FAILED",now,{recoveryPoint:"PATCH_REJECTED",receipt:{providerPatchCount:1,statusCode:patch.status}});return NextResponse.json({error:"PDT_BOBA_001_B01_PATCH_REJECTED",providerPatchCount:1},{status:502})}let after:State|null=null;try{after=await readState(token,f)}catch{}if(after&&finalMatches(after)){const done=await recordOperationResult(repo,begun.record.operationId,begun.record.requestHash,"SUCCEEDED",runtime.now?.()??new Date().toISOString(),{receipt:{providerPatchCount:1,updateStatusCode:patch?.status??null,readBackStatus:after.statuses,verified:{description:"PASS",protectedState:"PASS"}}});return NextResponse.json({status:patch?.ok?"UPDATED_AND_VERIFIED":"RECONCILED",mode:"WRITE_ONCE",operationId:done.operationId,requestHash:done.requestHash,ledgerStatus:done.status,providerPatchCount:1,receipt:done.receipt})}const pending=await recordOperationResult(repo,begun.record.operationId,begun.record.requestHash,"RECONCILIATION_REQUIRED",runtime.now?.()??new Date().toISOString(),{recoveryPoint:"POST_PATCH_READBACK",receipt:{providerPatchCount:1,updateStatusCode:patch?.status??null}});return NextResponse.json({error:"PDT_BOBA_001_B01_RECONCILIATION_REQUIRED",requestHash:pending.requestHash,providerPatchCount:1},{status:202})}
