import { neon } from "@neondatabase/serverless";
import { FACTORY_DOMAIN_SCHEMA_VERSION, validatePerformanceSnapshot, type PerformanceMetrics, type PerformanceSnapshot } from "./factory-domain-schemas";

export const PERFORMANCE_SNAPSHOT_RECORD_VERSION = "1.0.0" as const;
const FIELDS = ["views","visits","favorites","orders","revenue","conversionRate","etsySearchVisits"] as const satisfies readonly (keyof PerformanceMetrics)[];
export type MetricObservation = number | "NOT_AVAILABLE";
export type PerformanceObservations = Record<keyof PerformanceMetrics, MetricObservation>;
export type PerformanceSnapshotRecord = { schemaVersion:typeof PERFORMANCE_SNAPSHOT_RECORD_VERSION; snapshot:PerformanceSnapshot; baselineSnapshotId?:string; deltas:Record<keyof PerformanceMetrics,number|null>; deltaUnavailableFields:readonly (keyof PerformanceMetrics)[]; };
function clone<T>(v:T):T{return structuredClone(v);}
function required(v:string,c:string){const n=v.normalize("NFC").trim();if(!n)throw new Error(c);return n;}
export function createPerformanceSnapshotRecord(input:{snapshotId:string;productId:string;listingId:string;windowStart:string;windowEnd:string;observations:PerformanceObservations},baseline?:PerformanceSnapshotRecord):PerformanceSnapshotRecord{
  const unavailableFields=FIELDS.filter(f=>input.observations[f]==="NOT_AVAILABLE");const metrics=Object.fromEntries(FIELDS.map(f=>[f,input.observations[f]==="NOT_AVAILABLE"?null:input.observations[f]])) as PerformanceMetrics;
  const snapshot=validatePerformanceSnapshot({schemaVersion:FACTORY_DOMAIN_SCHEMA_VERSION,snapshotId:input.snapshotId,productId:input.productId,listingId:input.listingId,windowStart:input.windowStart,windowEnd:input.windowEnd,metrics,unavailableFields});
  if(baseline&&(baseline.snapshot.productId!==snapshot.productId||baseline.snapshot.listingId!==snapshot.listingId))throw new Error("PERFORMANCE_BASELINE_IDENTITY_MISMATCH");
  if(baseline&&Date.parse(baseline.snapshot.windowEnd)>Date.parse(snapshot.windowEnd))throw new Error("PERFORMANCE_BASELINE_AFTER_CURRENT");
  const deltaUnavailableFields:(keyof PerformanceMetrics)[]=[];const deltas={} as Record<keyof PerformanceMetrics,number|null>;for(const f of FIELDS){const a=snapshot.metrics[f],b=baseline?.snapshot.metrics[f]??null;if(!baseline||a===null||b===null){deltas[f]=null;deltaUnavailableFields.push(f);}else deltas[f]=Number((a-b).toFixed(6));}
  return Object.freeze({schemaVersion:PERFORMANCE_SNAPSHOT_RECORD_VERSION,snapshot:Object.freeze(snapshot),...(baseline?{baselineSnapshotId:baseline.snapshot.snapshotId}:{}),deltas:Object.freeze(deltas),deltaUnavailableFields:Object.freeze(deltaUnavailableFields.sort())});
}
export interface PerformanceSnapshotRepository{load(snapshotId:string):Promise<PerformanceSnapshotRecord|null>;save(record:PerformanceSnapshotRecord):Promise<void>;listForListing(listingId:string):Promise<PerformanceSnapshotRecord[]>;}
export class MemoryPerformanceSnapshotRepository implements PerformanceSnapshotRepository{private m=new Map<string,PerformanceSnapshotRecord>();async load(id:string){const r=this.m.get(id);return r?clone(r):null;}async save(r:PerformanceSnapshotRecord){if(this.m.has(r.snapshot.snapshotId)){const e=this.m.get(r.snapshot.snapshotId)!;if(JSON.stringify(e)!==JSON.stringify(r))throw new Error("PERFORMANCE_SNAPSHOT_ID_CONFLICT");return;}this.m.set(r.snapshot.snapshotId,clone(r));}async listForListing(id:string){return [...this.m.values()].filter(r=>r.snapshot.listingId===id).sort((a,b)=>a.snapshot.windowEnd.localeCompare(b.snapshot.windowEnd)||a.snapshot.snapshotId.localeCompare(b.snapshot.snapshotId,"en")).map(clone);}}
function sql(){const u=process.env.DATABASE_URL?.trim();if(!u)throw new Error("DATABASE_URL_NOT_CONFIGURED");return neon(u);}
export class NeonPerformanceSnapshotRepository implements PerformanceSnapshotRepository{private async ensure(){const q=sql();await q`CREATE TABLE IF NOT EXISTS performance_snapshots (snapshot_id text PRIMARY KEY, listing_id text NOT NULL, window_end timestamptz NOT NULL, record_json jsonb NOT NULL)`;}async load(id:string){await this.ensure();const q=sql();const rows=await q`SELECT record_json FROM performance_snapshots WHERE snapshot_id=${id} LIMIT 1`;return rows[0]?clone((rows[0] as any).record_json as PerformanceSnapshotRecord):null;}async save(r:PerformanceSnapshotRecord){await this.ensure();const q=sql(),json=JSON.stringify(r);const existing=await this.load(r.snapshot.snapshotId);if(existing){if(JSON.stringify(existing)!==json)throw new Error("PERFORMANCE_SNAPSHOT_ID_CONFLICT");return;}await q`INSERT INTO performance_snapshots(snapshot_id,listing_id,window_end,record_json) VALUES(${r.snapshot.snapshotId},${r.snapshot.listingId},${r.snapshot.windowEnd},${json}::jsonb)`;}async listForListing(id:string){await this.ensure();const q=sql();const rows=await q`SELECT record_json FROM performance_snapshots WHERE listing_id=${id} ORDER BY window_end ASC,snapshot_id ASC`;return rows.map(r=>clone((r as any).record_json as PerformanceSnapshotRecord));}}
