import { createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { PD_STOCK_005_VISUAL_R02_RELEASE } from "../../../../../../../../lib/pd-stock-005-visual-r02-release";
import { stageAuthorizedAssetChunk } from "../../../../../../../../lib/authorized-operation-asset-store";

export const runtime="nodejs";
export const dynamic="force-dynamic";

const ISSUER="https://token.actions.githubusercontent.com";
const AUDIENCE="https://autodigitalpublisher.vercel.app/api/internal/etsy/pd-stock-005/r02/visual-release/stage-from-url";
const REPOSITORY="chutcpoo/etsymonery";
const REF="refs/heads/pd-stock-005-release-runner";
const EVENT="push";
const WORKFLOW_REF="chutcpoo/etsymonery/.github/workflows/pd-stock-005-r02-release-runner.yml@refs/heads/pd-stock-005-release-runner";
type Header={alg?:string;kid?:string};type Claims={iss?:string;aud?:string|string[];exp?:number;nbf?:number;repository?:string;ref?:string;event_name?:string;workflow_ref?:string};type Jwk=JsonWebKey&{kid?:string};
const decode=<T,>(s:string)=>JSON.parse(Buffer.from(s,"base64url").toString("utf8")) as T;
const audOk=(aud:Claims["aud"])=>typeof aud==="string"?aud===AUDIENCE:Array.isArray(aud)&&aud.includes(AUDIENCE);
async function verifyOidc(token:string){const p=token.split(".");if(p.length!==3)throw new Error("PD_STOCK_R02_STAGE_OIDC_MALFORMED");const[h,c,s]=p,header=decode<Header>(h),claims=decode<Claims>(c);if(header.alg!=="RS256"||!header.kid)throw new Error("PD_STOCK_R02_STAGE_OIDC_HEADER_INVALID");if(claims.iss!==ISSUER||!audOk(claims.aud))throw new Error("PD_STOCK_R02_STAGE_OIDC_ORIGIN_INVALID");const now=Math.floor(Date.now()/1000);if(!claims.exp||claims.exp<now-30||(claims.nbf&&claims.nbf>now+30))throw new Error("PD_STOCK_R02_STAGE_OIDC_TIME_INVALID");if(claims.repository!==REPOSITORY||claims.ref!==REF||claims.event_name!==EVENT||claims.workflow_ref!==WORKFLOW_REF)throw new Error("PD_STOCK_R02_STAGE_OIDC_SCOPE_INVALID");const discovery=await fetch(`${ISSUER}/.well-known/openid-configuration`,{cache:"no-store"});if(!discovery.ok)throw new Error("PD_STOCK_R02_STAGE_OIDC_DISCOVERY_FAILED");const cfg=await discovery.json() as {jwks_uri?:string};if(!cfg.jwks_uri)throw new Error("PD_STOCK_R02_STAGE_OIDC_JWKS_URI_MISSING");const jr=await fetch(cfg.jwks_uri,{cache:"no-store"});if(!jr.ok)throw new Error("PD_STOCK_R02_STAGE_OIDC_JWKS_FAILED");const key=((await jr.json() as {keys?:Jwk[]}).keys??[]).find(k=>k.kid===header.kid&&k.kty==="RSA");if(!key)throw new Error("PD_STOCK_R02_STAGE_OIDC_KEY_NOT_FOUND");const pk=await crypto.subtle.importKey("jwk",key,{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["verify"]);if(!await crypto.subtle.verify("RSASSA-PKCS1-v1_5",pk,Buffer.from(s,"base64url"),new TextEncoder().encode(`${h}.${c}`)))throw new Error("PD_STOCK_R02_STAGE_OIDC_SIGNATURE_INVALID");}
function jpegDimensions(bytes:Buffer){if(bytes.length<4||bytes[0]!==0xff||bytes[1]!==0xd8)return null;let o=2;while(o+9<bytes.length){if(bytes[o]!==0xff){o++;continue}const m=bytes[o+1];o+=2;if(m===0xd8||m===0xd9)continue;if(o+2>bytes.length)return null;const len=bytes.readUInt16BE(o);if(len<2||o+len>bytes.length)return null;const sof=(m>=0xc0&&m<=0xc3)||(m>=0xc5&&m<=0xc7)||(m>=0xc9&&m<=0xcb)||(m>=0xcd&&m<=0xcf);if(sof&&len>=7)return{height:bytes.readUInt16BE(o+3),width:bytes.readUInt16BE(o+5)};o+=len}return null;}
function sourceAllowed(value:string){try{const u=new URL(value);return u.protocol==="https:"&&(u.hostname.endsWith(".oaiusercontent.com")||u.hostname==="oaiusercontent.com");}catch{return false}}
export async function POST(request:Request){const authorization=request.headers.get("authorization")?.trim()??"";if(!authorization.startsWith("Bearer "))return NextResponse.json({error:"PD_STOCK_R02_STAGE_OIDC_MISSING",ETSY_WRITE_COUNT:0},{status:401});try{await verifyOidc(authorization.slice(7).trim())}catch(error){return NextResponse.json({error:error instanceof Error?error.message:"PD_STOCK_R02_STAGE_OIDC_INVALID",ETSY_WRITE_COUNT:0},{status:401})}let payload:unknown;try{payload=await request.json()}catch{return NextResponse.json({error:"PD_STOCK_R02_STAGE_INVALID_JSON",ETSY_WRITE_COUNT:0},{status:400})}if(!payload||typeof payload!=="object"||Array.isArray(payload))return NextResponse.json({error:"PD_STOCK_R02_STAGE_INVALID_PAYLOAD",ETSY_WRITE_COUNT:0},{status:400});const v=payload as Record<string,unknown>,operationId=typeof v.operationId==="string"?v.operationId:"",confirmation=typeof v.confirmation==="string"?v.confirmation:"",assetSha256=typeof v.assetSha256==="string"?v.assetSha256.trim().toLowerCase():"",sourceUrl=typeof v.sourceUrl==="string"?v.sourceUrl:"";if(operationId!==PD_STOCK_005_VISUAL_R02_RELEASE.operationId||confirmation!==operationId)return NextResponse.json({error:"PD_STOCK_R02_STAGE_OPERATION_CONFIRMATION_MISMATCH",ETSY_WRITE_COUNT:0},{status:409});const asset=PD_STOCK_005_VISUAL_R02_RELEASE.gallery.find(a=>a.sha256===assetSha256);if(!asset)return NextResponse.json({error:"PD_STOCK_R02_STAGE_ASSET_NOT_REGISTERED",ETSY_WRITE_COUNT:0},{status:409});if(!sourceAllowed(sourceUrl))return NextResponse.json({error:"PD_STOCK_R02_STAGE_SOURCE_NOT_ALLOWED",ETSY_WRITE_COUNT:0},{status:409});let response:Response;try{response=await fetch(sourceUrl,{method:"GET",cache:"no-store",redirect:"follow"})}catch{return NextResponse.json({error:"PD_STOCK_R02_STAGE_SOURCE_FETCH_FAILED",ETSY_WRITE_COUNT:0},{status:502})}if(!response.ok)return NextResponse.json({error:"PD_STOCK_R02_STAGE_SOURCE_FETCH_REJECTED",sourceStatus:response.status,ETSY_WRITE_COUNT:0},{status:502});const bytes=Buffer.from(await response.arrayBuffer()),sha=createHash("sha256").update(bytes).digest("hex"),dims=jpegDimensions(bytes);if(bytes.length!==asset.byteSize||sha!==asset.sha256||!dims||dims.width!==asset.width||dims.height!==asset.height)return NextResponse.json({error:"PD_STOCK_R02_STAGE_SOURCE_IDENTITY_MISMATCH",actualBytes:bytes.length,actualSha256:sha,actualDimensions:dims,ETSY_WRITE_COUNT:0},{status:409});const chunkSize=40000,chunkCount=Math.ceil(bytes.length/chunkSize);for(let chunkIndex=0;chunkIndex<chunkCount;chunkIndex++){const part=bytes.subarray(chunkIndex*chunkSize,Math.min(bytes.length,(chunkIndex+1)*chunkSize));await stageAuthorizedAssetChunk({operationId,assetSha256,chunkIndex,chunkCount,dataBase64:part.toString("base64")});}return NextResponse.json({status:"ASSET_STAGED_AND_VERIFIED",operationId,assetSha256,byteSize:bytes.length,width:dims.width,height:dims.height,chunkCount,ETSY_WRITE_COUNT:0});}
